ant-design/ant-design-web3

packages/web3/src/address/index.md
packages/web3/src/address/index.tsx
packages/web3/src/address/index.zh-CN.md

feat: Update docs about address & Add tooltip when hover address

---

packages/web3/src/address/demos/copyable.tsx
packages/web3/src/address/index.md
packages/web3/src/address/index.tsx
packages/web3/src/address/index.zh-CN.md

- https://github.com/ant-design/ant-design-web3/pull/52#discussion_r1359028807

feat: optimize api about address's ellipsis

---

.dumi/app.tsx
packages/common/global.d.ts
packages/common/src/rpc-providers/zan.ts
packages/common/src/types.ts
packages/common/src/wallets/meta-mask.ts
packages/common/src/wallets/wallet-connect.ts
packages/common/src/web3-config-provider/context.ts
packages/common/src/web3-config-provider/index.tsx
packages/ethereum/src/eip1193-provider.ts
packages/ethereum/src/ethereum-provider.ts
packages/ethereum/src/index.ts
packages/ethereum/src/universal-provider.ts
packages/ethereum/src/web3-provider.tsx
packages/web3/src/connect-button/unconnected-button.tsx
packages/web3/src/connect-modal/components/QrCode.tsx
packages/web3/src/connect-modal/components/WalletList.tsx
packages/web3/src/connect-modal/context/index.ts
packages/web3/src/connect-modal/demos/basic.tsx
packages/web3/src/connect-modal/demos/dark.tsx
packages/web3/src/connect-modal/demos/simple.tsx
packages/web3/src/connect-modal/index.tsx
packages/web3/src/connect-modal/interface.ts
packages/web3/src/connect-modal/utils/index.ts
packages/web3/src/constants/presets.ts
packages/web3/src/hooks/useWallets.ts
packages/web3/src/mock-provider/index.ts

重新定义了 `Connect`，把获取二维码的接口放在里面了。

feat: support show qrcode in ConnectModal

---

packages/common/src/types.ts
packages/ethereum/src/universal-provider.ts
packages/wagmi/src/wagmi-provider/config-provider.tsx
packages/wagmi/src/wagmi-provider/index.test.tsx
packages/wagmi/src/wagmi-provider/index.tsx
packages/web3/src/connect-button/connect-button.tsx
packages/web3/src/connector/__tests__/basic.test.tsx
packages/web3/src/connector/__tests__/chains.test.tsx
packages/web3/src/connector/conector.tsx
packages/web3/src/connector/demos/chains.tsx
packages/web3/src/connector/demos/wagmi.tsx
packages/web3/src/connector/index.zh-CN.md
packages/web3/src/connector/interface.ts
packages/web3/src/web3-config-provider/demos/simple.tsx

feat: support switchChain

---

packages/web3/src/address/index.tsx
packages/web3/src/address/style/index.ts
packages/web3/src/connect-button/__tests__/__snapshots__/profile-modal.test.tsx.snap
packages/web3/src/connect-button/__tests__/index.test.tsx
packages/web3/src/connect-button/__tests__/profile-modal.test.tsx
packages/web3/src/connect-button/connect-button.tsx
packages/web3/src/connect-button/profile-modal.tsx
packages/web3/src/connect-button/tooltip.tsx
packages/web3/src/utils/browser.ts
packages/web3/src/utils/index.ts

feat: add user profile modal in ConnectButton

---

packages/web3/src/connect-button/connect-button.tsx

fix: Duplicate Tooltip

---

README.md
docs/guide/index.md
docs/guide/index.zh-CN.md
docs/guide/theme.md
docs/index.zh-CN.md

docs: fine-tune markdown

---

packages/web3/src/connect-modal/demos/theme.tsx
packages/web3/src/connect-modal/index.md
packages/web3/src/connect-modal/index.zh-CN.md
packages/web3/src/connect-modal/style/index.tsx

优化 ConnectModal 的主题 token,让主题色可以更方便控制内部元素的样式

feat: optimize connect-modal theme token

---

packages/web3/src/browser-link/index.md
packages/web3/src/browser-link/index.zh-CN.md

feat: 完善browser-link组件文档

---

packages/icons/package.json

close https://github.com/ant-design/ant-design-web3/issues/120

fix: disable father cache in icon package for fix hotreload

---

packages/web3/src/connector/index.md
packages/web3/src/connector/index.zh-CN.md

feat: 完善connector 英文文档

---

packages/web3/src/browser-link/index.md
packages/web3/src/browser-link/index.zh-CN.md

BrowserLink组件：
1. API markdown格式修复 
2. API 英文翻译

fix: API markdown格式修复

---

packages/web3/src/address/index.md
packages/web3/src/address/index.zh-CN.md
packages/web3/src/browser-link/index.md
packages/web3/src/browser-link/index.zh-CN.md
packages/web3/src/connect-button/index.md
packages/web3/src/connect-button/index.zh-CN.md
packages/web3/src/connect-modal/index.md
packages/web3/src/connect-modal/index.zh-CN.md
packages/web3/src/connector/index.md
packages/web3/src/connector/index.zh-CN.md
packages/web3/src/icons/index.md
packages/web3/src/icons/index.zh-CN.md
packages/web3/src/nft-image/index.md
packages/web3/src/nft-image/index.zh-CN.md
packages/web3/src/web3-config-provider/index.md
packages/web3/src/web3-config-provider/index.zh-CN.md

Components category:
- General 通用
- Connect 连接
- Display 展示
- Advanced 高级

docs: update components category

---

packages/web3/src/nft-image/index.md
packages/web3/src/nft-image/index.zh-CN.md

NFTImage组件：
1. 完善 NFTImage组件文档

feat: 完善 NFTImage组件文档

---

packages/web3/src/browser-link/index.md

docs: doc error

---

packages/web3/src/nft-image/demos/simple.tsx
packages/web3/src/nft-image/demos/wagmi.tsx

feat: update Image demo

---

packages/web3/src/browser-link/__tests__/index.test.tsx
packages/web3/src/browser-link/demos/customName.tsx
packages/web3/src/browser-link/index.md
packages/web3/src/browser-link/index.tsx
packages/web3/src/browser-link/index.zh-CN.md

feat: browser link support name

---

packages/common/src/types.ts
packages/web3/src/connect-button/__tests__/menu.test.tsx
packages/web3/src/connect-button/__tests__/profile-modal.test.tsx
packages/web3/src/connect-button/chain-select.tsx
packages/web3/src/connect-button/connect-button.tsx
packages/web3/src/connector/__tests__/basic.test.tsx
packages/web3/src/connector/conector.tsx
packages/web3/src/connector/demos/basic.tsx
packages/web3/src/connector/index.md
packages/web3/src/connector/index.zh-CN.md

feat: Opt connect button

---

packages/web3/src/connect-button/demos/avatar.tsx
packages/web3/src/connect-button/index.md
packages/web3/src/connect-button/index.zh-CN.md

feat: update demo about connect-button avatar

---

packages/web3/src/connect-button/__tests__/__snapshots__/profile-modal.test.tsx.snap
packages/web3/src/connect-button/profile-modal.tsx

feat: optimize profile-modal style

---

packages/web3/src/nft-card/index.md
packages/web3/src/nft-card/index.zh-CN.md

docs: update NFTCard API doc

---

packages/common/src/utils/format.ts
packages/web3/src/hooks/useNFT.ts
packages/web3/src/nft-card/NFTCard.tsx
packages/web3/src/nft-card/__tests__/basic.test.tsx
packages/web3/src/nft-card/demos/wagmi.tsx
packages/web3/src/nft-card/index.md
packages/web3/src/nft-card/index.zh-CN.md

feat: NFTCard support address and tokenId

---

packages/common/src/utils/index.ts
packages/web3/src/nft-image/__tests__/__snapshots__/index.test.tsx.snap
packages/web3/src/nft-image/__tests__/index.test.tsx
packages/web3/src/nft-image/demos/customGetNFTMetadata.tsx
packages/web3/src/nft-image/index.md
packages/web3/src/nft-image/index.tsx
packages/web3/src/nft-image/index.zh-CN.md

feat: image support custom getNFTMetadata

---

.changeset/ninety-coins-walk.md
packages/web3/src/hooks/__tests__/useConnection.test.tsx
packages/web3/src/hooks/demos/useConnection.tsx
packages/web3/src/hooks/index.md
packages/web3/src/hooks/index.tsx
packages/web3/src/hooks/index.zh-CN.md
packages/web3/src/hooks/useConnection.ts

close https://github.com/ant-design/ant-design-web3/issues/208

feat: add useConnection hook

---

.changeset/tasty-pigs-shout.md
packages/web3/src/nft-card/NFTCard.tsx
packages/web3/src/nft-card/style/index.tsx

feat: NFTCard show Skeleton when request metadata

---

.changeset/wise-ads-fetch.md
packages/assets/src/wallets/coinbase-wallet.tsx
packages/assets/src/wallets/index.ts
packages/wagmi/src/wallets/coinbase-wallet.test.tsx
packages/wagmi/src/wallets/coinbase-wallet.tsx
packages/wagmi/src/wallets/index.ts
packages/web3/src/connect-modal/__tests__/__snapshots__/basic.test.tsx.snap
packages/web3/src/connect-modal/__tests__/basic.test.tsx
packages/web3/src/connect-modal/style/index.tsx
packages/web3/src/connect-modal/utils/index.test.ts
packages/web3/src/connect-modal/utils/index.ts
packages/web3/src/wagmi/demos/basic.tsx

close https://github.com/ant-design/ant-design-web3/issues/146

feat: support CoinbaseWallet

---

packages/web3/src/nft-card/NFTCard.tsx
packages/web3/src/nft-card/__tests__/basic.test.tsx

close: https://github.com/ant-design/ant-design-web3/issues/222
1. 增加单测
2. 解决冲突

feat: Hide balance and like icon when it not config in NFTCard

---

docs/home/components/Features/index.module.less
docs/home/components/Features/index.tsx

site: site features

---

.changeset/strange-turtles-refuse.md
packages/assets/src/chains.tsx
packages/common/src/types.ts
packages/web3/src/connect-button/__tests__/balance.test.tsx
packages/web3/src/connect-button/__tests__/profile-modal.test.tsx
packages/web3/src/connect-button/connect-button.tsx
packages/web3/src/connect-button/profile-modal.tsx
packages/web3/src/crypto-price/__tests__/basic.test.tsx
packages/web3/src/crypto-price/balance.tsx
packages/web3/src/crypto-price/demos/basic.tsx
packages/web3/src/crypto-price/demos/custom-chain.tsx
packages/web3/src/crypto-price/index.md
packages/web3/src/crypto-price/index.tsx
packages/web3/src/crypto-price/index.zh-CN.md
packages/web3/src/crypto-price/style/index.ts
packages/web3/src/index.ts
packages/web3/src/nft-card/NFTCard.tsx
packages/web3/src/nft-card/__tests__/basic.test.tsx
packages/web3/src/nft-card/demos/basic.tsx
packages/web3/src/nft-card/demos/dark-mode.tsx
packages/web3/src/nft-card/index.md
packages/web3/src/nft-card/index.zh-CN.md
packages/web3/src/nft-card/style/index.tsx

use in components ConnectButton and NFTCard

feat: New component CryptoPrice 🚀

---

.changeset/brown-seas-cheer.md
docs/home/components/Theme/index.module.less
docs/home/components/Theme/index.tsx
packages/web3/src/connect-modal/__tests__/__snapshots__/basic.test.tsx.snap
packages/web3/src/connect-modal/__tests__/__snapshots__/simple.test.tsx.snap
packages/web3/src/connect-modal/__tests__/basic.test.tsx
packages/web3/src/connect-modal/components/ModalPanel.tsx
packages/web3/src/connect-modal/index.tsx
packages/web3/src/connect-modal/style/index.tsx

`ConnectModal.ModalPanel` 暴露出来，有的场景可能会用到。
另外我们自己的官网也会用到。

feat: export ConnectModal.ModalPanel and use it in home page

---

.changeset/heavy-zoos-reflect.md
packages/web3/src/connect-modal/style/index.tsx

feat: optimize connect modal style

---

.changeset/six-wombats-report.md
packages/common/src/types.ts
packages/wagmi/src/wagmi-provider/__test__/balance.test.tsx
packages/wagmi/src/wagmi-provider/__test__/basic.test.tsx
packages/wagmi/src/wagmi-provider/config-provider.tsx
packages/wagmi/src/wagmi-provider/index.tsx
packages/web3/src/connect-button/__tests__/balance.test.tsx
packages/web3/src/connect-button/__tests__/profile-modal.test.tsx
packages/web3/src/connect-button/connect-button.tsx
packages/web3/src/connect-button/demos/balance.tsx
packages/web3/src/connector/conector.tsx
packages/web3/src/crypto-price/balance.tsx
packages/web3/src/crypto-price/index.md
packages/web3/src/crypto-price/index.zh-CN.md
packages/web3/src/wagmi/demos/balance.tsx
packages/web3/src/wagmi/index.md
packages/web3/src/wagmi/index.zh-CN.md
packages/web3/src/web3-config-provider/__tests__/index.test.tsx

close https://github.com/ant-design/ant-design-web3/issues/215

feat: Ethereum adapter @ant-design/web3-wagmi support balance

---

packages/icons/package.json
packages/icons/src/__tests__/__snapshots__/index.test.tsx.snap
packages/icons/src/__tests__/iconTest.tsx
packages/icons/src/__tests__/index.test.tsx
pnpm-lock.yaml

test: icons test

---

.changeset/silver-phones-guess.md
packages/web3/src/connect-button/__tests__/index.test.tsx
packages/web3/src/connect-button/connect-button.tsx

This is the PR about implementation of display avatar in connect button.

show avatar in connect button

---

package.json
packages/icons/package.json
packages/web3/package.json
packages/web3/src/address/__tests__/__snapshots__/index.test.tsx.snap
packages/web3/src/connect-button/__tests__/__snapshots__/menu.test.tsx.snap
packages/web3/src/connect-button/__tests__/__snapshots__/profile-modal.test.tsx.snap
packages/web3/src/connect-button/__tests__/__snapshots__/tooltip.test.tsx.snap
packages/web3/src/connect-button/__tests__/index.test.tsx
packages/web3/src/connect-button/__tests__/profile-modal.test.tsx
packages/web3/src/connect-button/connect-button.tsx
packages/web3/src/connect-button/demos/avatar.tsx
packages/web3/src/connect-button/demos/menu.tsx
packages/web3/src/connect-button/style/index.ts
packages/web3/src/connect-modal/__tests__/__snapshots__/basic.test.tsx.snap
packages/web3/src/connect-modal/__tests__/__snapshots__/simple.test.tsx.snap
packages/web3/src/nft-image/__tests__/__snapshots__/index.test.tsx.snap
packages/web3/src/web3-config-provider/__tests__/__snapshots__/index.test.tsx.snap
pnpm-lock.yaml

refactor: avatar in ConnectButton

---

docs/home/components/Theme/index.module.less
docs/home/components/Theme/index.tsx
docs/home/index.tsx

site: theme mode follow prefers color

---

.vscode/settings.json
docs/home/components/Features/index.module.less
docs/home/components/Features/index.tsx

feat: ui debug about site features

---

docs/home/components/ShowCase/connect.module.less
docs/home/components/ShowCase/index.module.less
docs/home/components/Theme/index.module.less
docs/home/index.module.less

fix: optimize show case style in mobile

---

.dumi/theme/builtins/IconSearch/IconSearch.tsx

docs: icons doc filter bar only show icon in mobile

---

.changeset/tidy-foxes-glow.md
packages/web3/src/connect-modal/__tests__/__snapshots__/basic.test.tsx.snap
packages/web3/src/connect-modal/components/QrCode.tsx
packages/web3/src/connect-modal/style/index.tsx

fix: ConnectModal QrCode link style

---

.dumi/app.tsx
docs/home/components/Banner/index.module.less
docs/home/components/Banner/index.tsx
docs/home/components/Theme/index.module.less

close #307
* fix banner styles
* fix banner button text intl

docs: fix Home Banner styles

---

.changeset/perfect-bees-rescue.md
docs/guide/demos/custom-token.tsx
docs/guide/demos/theme.tsx
docs/home/components/ShowCase/Connect.tsx
docs/home/components/Theme/index.tsx
packages/web3/src/connect-modal/__tests__/__snapshots__/basic.test.tsx.snap
packages/web3/src/connect-modal/__tests__/__snapshots__/simple.test.tsx.snap
packages/web3/src/connect-modal/__tests__/basic.test.tsx
packages/web3/src/connect-modal/__tests__/mode.test.tsx
packages/web3/src/connect-modal/__tests__/panel.test.tsx
packages/web3/src/connect-modal/components/DefaultGuidePanel.tsx
packages/web3/src/connect-modal/components/MainPanel.tsx
packages/web3/src/connect-modal/components/ModalPanel.tsx
packages/web3/src/connect-modal/context/index.ts
packages/web3/src/connect-modal/demos/basic.tsx
packages/web3/src/connect-modal/demos/panel.tsx
packages/web3/src/connect-modal/demos/simple.tsx
packages/web3/src/connect-modal/hooks/useMode.test.tsx
packages/web3/src/connect-modal/hooks/useMode.ts
packages/web3/src/connect-modal/index.md
packages/web3/src/connect-modal/index.tsx
packages/web3/src/connect-modal/index.zh-CN.md
packages/web3/src/connect-modal/interface.ts
packages/web3/src/connect-modal/style/index.tsx
packages/web3/src/connector/demos/basic.tsx
packages/web3/src/wagmi/demos/balance.tsx
packages/web3/src/wagmi/demos/basic.tsx
packages/web3/src/wagmi/demos/more-wallets.tsx
packages/web3/src/wagmi/demos/uiconfig.tsx

feat: ConnectModal support mode

---

.changeset/brown-berries-leave.md
packages/web3/src/connect-modal/components/DefaultGuidePanel.tsx
packages/web3/src/connect-modal/components/MainPanel.tsx
packages/web3/src/connect-modal/components/ModalPanel.tsx
packages/web3/src/connect-modal/components/QrCode.tsx
packages/web3/src/connect-modal/interface.ts
packages/web3/src/connect-modal/style/index.tsx

fix: qrcode style bug in simple ConnectModal

---

.changeset/eighty-dogs-wonder.md
docs/guide/demos/adapter.tsx
packages/web3/src/connect-button/demos/basic.tsx
packages/web3/src/connect-modal/__tests__/__snapshots__/basic.test.tsx.snap
packages/web3/src/connect-modal/__tests__/get-wallet.test.tsx
packages/web3/src/connect-modal/__tests__/qrcode.test.tsx
packages/web3/src/connect-modal/components/GetWalletPanel.tsx
packages/web3/src/connect-modal/components/MainPanel.tsx
packages/web3/src/connect-modal/components/QrCode.tsx
packages/web3/src/connect-modal/components/WalletCard.tsx
packages/web3/src/connect-modal/components/WalletList.tsx
packages/web3/src/connect-modal/context/index.ts
packages/web3/src/connect-modal/index.tsx
packages/web3/src/connect-modal/interface.ts
packages/web3/src/connect-modal/style/index.tsx
packages/web3/src/connect-modal/utils/index.ts

close https://github.com/ant-design/ant-design-web3/issues/314

fix: Get wallet dowload bug

---

.changeset/odd-islands-sin.md
packages/web3/src/connect-modal/__tests__/panel.test.tsx
packages/web3/src/connect-modal/components/ModalPanel.tsx
packages/web3/src/connect-modal/index.tsx

close https://github.com/ant-design/ant-design-web3/issues/314

fix: Get wallet button not work in ConnectModal panel mode

---

docs/home/components/Theme/index.module.less
docs/home/components/Theme/index.tsx
docs/home/index.module.less

docs: add color theme demo for index page

---

.changeset/silly-jokes-search.md
packages/web3/src/address/style/index.ts
packages/web3/src/connect-button/__tests__/theme.test.tsx
packages/web3/src/connect-button/demos/type.tsx
packages/web3/src/connect-modal/__tests__/theme.test.tsx

fix: ConnectButton text color bug when type is primary

---

.changeset/proud-grapes-sneeze.md
packages/wagmi/src/wagmi-provider/__test__/switch-chain-unconnected.test.tsx
packages/wagmi/src/wagmi-provider/__test__/switch-chain.test.tsx
packages/wagmi/src/wagmi-provider/config-provider.tsx
packages/wagmi/src/wagmi-provider/index.tsx

fix: switch chain not work

---

packages/web3/src/address/__tests__/index.test.tsx

1. does not display ellipsis if ellipsis is set to false
2. does not display tooltip if tooltip is set to false
3. does not apply any formatting if format is set to false

feat: add address test

---

packages/web3/src/connect-button/__tests__/profile-modal.test.tsx
packages/web3/src/connect-button/connect-button.tsx
packages/web3/src/connect-button/demos/menu.tsx
packages/web3/src/connect-button/style/index.ts

- 添加 user icon 为默认 icon
- 修复地址颜色问题

fix: ConnectButton profile icon style bug, use user icon by default

---

docs/home/components/ShowCase/Connect.tsx
docs/home/components/Theme/index.tsx

docs: Index page demo use coinbase wallet

---

packages/web3/src/nft-card/__tests__/basic.test.tsx

add: renders footer content when footer prop is provided

feat: add nft card test

---

packages/wagmi/src/wagmi-provider/config-provider.tsx
packages/web3/src/connect-modal/index.md

fix: Chain icon not show when use with wagmi

---

README.md

docs: update Contributing members image

---

packages/web3/src/connect-button/chain-select.tsx
packages/web3/src/connect-modal/demos/panel.tsx
packages/web3/src/connect-modal/demos/theme.tsx
packages/web3/src/connect-modal/index.tsx

fix: remove unused code

---

packages/assets/src/chains.tsx
packages/common/src/types.ts
packages/common/src/utils/createGetBrowserLink.test.ts
packages/common/src/utils/createGetBrowserLink.ts
packages/common/src/utils/index.ts

https://github.com/ant-design/ant-design-web3/issues/248

feat: add getBrowserLink fn to chains

---

docs/home/components/Banner/index.module.less
docs/home/components/Banner/index.tsx
docs/home/components/Features/index.module.less

docs: update index page title image

---

.changeset/gold-shrimps-buy.md
README.md
packages/assets/package.json
packages/common/package.json
packages/icons/package.json
packages/wagmi/package.json
packages/web3/package.json

Improve the package.json information and add a main field to accommodate more projects.
close #360

fix: Improve the package.json information and add a main field

---

packages/icons/src/__tests__/index.test.tsx

test: add icon path id test

---

docs/home/components/Theme/index.module.less
docs/home/components/Theme/index.tsx

https://github.com/ant-design/ant-design-web3/assets/10286961/9264f2d2-a33a-4918-bc36-71c0eb0b266a

site: optimize select theme

---

docs/guide/demos/quick-start.tsx

快速开始用免费的 json rpc 的服务，避免别人代码拷贝过去跑不起来。

docs: quick use public rpc provider

---

docs/home/components/ShowCase/ConnectButton.tsx

fix: chains cant switch

---

README-zh_CN.md
README.md

Readme not support insert a component.

docs: fix readme usage install bug

---

.changeset/real-chefs-protect.md
packages/common/src/locale/en_US.ts
packages/common/src/locale/zh_CN.ts
packages/common/src/types.ts
packages/web3/src/nft-card/NFTCard.tsx
packages/web3/src/nft-card/__tests__/action.test.tsx
packages/web3/src/nft-card/index.md
packages/web3/src/nft-card/index.zh-CN.md

feat: NFTCard support intl

---

README-zh_CN.md
README.md

docs: Docs opt readme

---

.changeset/violet-badgers-drop.md
.github/workflows/changeset-check.yml

我自己的仓库尝试了一下，修改前也是无法获取文件变更，修改后就可以正常获取了

ci: changeset check

---

.changeset/good-vans-rule.md
docs/guide/demos/adapter.tsx
packages/common/src/types.ts
packages/wagmi/src/interface.ts
packages/wagmi/src/wagmi-provider/__tests__/config-with-universal-wallet.test.tsx
packages/wagmi/src/wagmi-provider/__tests__/connect-with-universal-wallet.test.tsx
packages/wagmi/src/wagmi-provider/config-provider.tsx
packages/wagmi/src/wagmi-provider/index.tsx
packages/wagmi/src/wallets/__tests__/token-pocket.test.tsx
packages/wagmi/src/wallets/__tests__/universal-wallet.test.tsx
packages/wagmi/src/wallets/index.ts
packages/wagmi/src/wallets/meta-mask.ts
packages/wagmi/src/wallets/safeheron.ts
packages/wagmi/src/wallets/token-pocket.tsx
packages/wagmi/src/wallets/universal-wallet.tsx
packages/wagmi/src/wallets/wallet-connect.ts
packages/web3/src/connect-modal/__tests__/extension-install.test.tsx
packages/web3/src/connect-modal/components/WalletList.tsx
packages/web3/src/wagmi/demos/custom-wallet.tsx
packages/web3/src/wagmi/demos/more-wallets.tsx
packages/web3/src/wagmi/demos/token-pocket.tsx
packages/web3/src/wagmi/index.md
packages/web3/src/wagmi/index.zh-CN.md

close https://github.com/ant-design/ant-design-web3/issues/414

feat: Add UniversalWallet for support TokenPocket and more wallets

---

packages/web3/src/web3-config-provider/index.md
packages/web3/src/web3-config-provider/index.zh-CN.md

docs: update docs about web3-config-provider's api

---

.changeset/empty-goats-ring.md
packages/web3/src/connect-button/__tests__/connect.test.tsx

test:Increase ConnectButton test coverage

---

docs/guide/contributing.md
docs/guide/contributing.zh-CN.md

For https://github.com/ant-design/ant-design-web3/discussions/404#discussioncomment-8061659

chore: add new core member thinkasany 🎉

---

.changeset/weak-geckos-develop.md
packages/web3/src/connector/__tests__/basic.test.tsx

test:Increase connector test coverage

---

.changeset/slow-forks-dance.md
packages/common/package.json
packages/common/src/types.ts
packages/common/src/web3-config-provider/index.tsx
packages/web3/src/web3-config-provider/__tests__/index.test.tsx
packages/web3/src/web3-config-provider/index.md
packages/web3/src/web3-config-provider/index.zh-CN.md
pnpm-lock.yaml

https://github.com/ant-design/ant-design-web3/issues/417

feat: support extending context from parent for web3-config-provider

---

.changeset/dry-seahorses-jog.md
packages/common/src/locale/en_US.ts
packages/common/src/locale/zh_CN.ts
packages/common/src/types.ts
packages/web3/src/address/__tests__/index.test.tsx
packages/web3/src/connect-button/__tests__/menu.test.tsx
packages/web3/src/connect-button/__tests__/tooltip.test.tsx
packages/web3/src/connect-button/connect-button.tsx
packages/web3/src/connect-button/profile-modal.tsx
packages/web3/src/connect-button/tooltip.tsx

fix: Modify the content of ConnectButton message #487

---

packages/common/package.json
pnpm-lock.yaml

fix: add lodash to @ant-design/web3-common dependencies

---

.changeset/lucky-suns-perform.md
packages/wagmi/src/interface.ts
packages/wagmi/src/utils.ts
packages/wagmi/src/wagmi-provider/__tests__/config-with-eip6963-and-wallets.test.tsx
packages/wagmi/src/wagmi-provider/__tests__/config-with-eip6963-wallet.test.tsx
packages/wagmi/src/wagmi-provider/config-provider.tsx
packages/wagmi/src/wagmi-provider/index.tsx
packages/wagmi/src/wallets/__tests__/eip6963.test.tsx
packages/wagmi/src/wallets/eip6963.tsx
packages/wagmi/src/wallets/index.ts
packages/web3/src/connect-modal/__tests__/get-wallet.test.tsx
packages/web3/src/connect-modal/components/GetWalletPanel.tsx
packages/web3/src/wagmi/demos/eip6963.tsx
packages/web3/src/wagmi/demos/more-wallets.tsx
packages/web3/src/wagmi/demos/token-pocket.tsx
packages/web3/src/wagmi/index.md
packages/web3/src/wagmi/index.zh-CN.md

close https://github.com/ant-design/ant-design-web3/issues/491

feat: support eip6963

---

.changeset/swift-bulldogs-lie.md
package.json
packages/web3/package.json
packages/web3/src/address/__tests__/__snapshots__/index.test.tsx.snap
packages/web3/src/connect-button/__tests__/__snapshots__/profile-modal.test.tsx.snap
packages/web3/src/connect-button/__tests__/__snapshots__/tooltip.test.tsx.snap
packages/web3/src/connect-modal/__tests__/__snapshots__/basic.test.tsx.snap
packages/web3/src/connect-modal/__tests__/__snapshots__/simple.test.tsx.snap
packages/web3/src/nft-image/__tests__/__snapshots__/index.test.tsx.snap
packages/web3/src/theme/useStyle/index.ts
packages/web3/src/web3-config-provider/__tests__/__snapshots__/index.test.tsx.snap
pnpm-lock.yaml

#516 
这段样式其实已经在antd中移除了，所以demo中出了问题，所以感觉还是升级一下antd，然后再去修复这个bug好了。
https://github.com/ant-design/ant-design/pull/46702/files
并且因为我们又包了一层div，所以footer下面的button也没按照antd给的margin距离。

feat: upgrade antd to 5.13.2 & @ant-design/cssinjs to 1.18.2

---

.changeset/nice-kids-hammer.md
packages/wagmi/src/wagmi-provider/__tests__/unconnected.test.tsx

test: Increase WagmiProvider test coverage

---

.changeset/young-brooms-pump.md
docs/course/contract-dapp.md
package.json
packages/common/src/utils/warning.ts
packages/web3/src/connect-modal/__tests__/basic.test.tsx
packages/web3/src/connect-modal/__tests__/mode.test.tsx
packages/web3/src/connect-modal/__tests__/panel.test.tsx
packages/web3/src/connect-modal/__tests__/simple.test.tsx
packages/web3/src/connect-modal/__tests__/theme.test.tsx
packages/web3/src/connect-modal/components/ModalPanel.tsx
packages/web3/src/connect-modal/components/WalletList.tsx
packages/web3/src/connect-modal/demos/basic.tsx
packages/web3/src/connect-modal/demos/customGuide.tsx
packages/web3/src/connect-modal/demos/panel.tsx
packages/web3/src/connect-modal/demos/simple.tsx
packages/web3/src/connect-modal/demos/ungroupedBasic.tsx
packages/web3/src/connect-modal/index.md
packages/web3/src/connect-modal/index.tsx
packages/web3/src/connect-modal/index.zh-CN.md
packages/web3/src/connect-modal/interface.ts
pnpm-lock.yaml

feat: ConnectModal support group configuration

---

packages/web3/src/address/index.zh-CN.md
packages/web3/src/connect-button/index.zh-CN.md
packages/web3/src/solana/index.zh-CN.md
packages/web3/src/wagmi/index.zh-CN.md

docs: unified translation

---

.dumirc.ts
package.json
packages/web3/global.d.ts
packages/web3/src/solana/demos/more-components.tsx

docs: fix Solana NFTCard demo

---

.changeset/sixty-carrots-sniff.md
package.json
packages/wagmi/src/wallets/__tests__/wallet-connect.test.tsx
packages/wagmi/src/wallets/wallet-connect.ts

close https://github.com/ant-design/ant-design-web3/issues/468

fix: cache WalletConnect qrcode uri for fix qrcode display bug

---

README-zh_CN.md
README.md

feat: add star history

---

.changeset/young-worms-repair.md
README-zh_CN.md
README.md
packages/wagmi/src/wallets/__tests__/universal-wallet.test.tsx
packages/wagmi/src/wallets/universal-wallet.tsx

similar issue like this: https://github.com/ant-design/ant-design-web3/pull/568

fix: UniversalWallet getQrCode bug on the second times

---

.changeset/empty-peaches-cover.md
.changeset/fast-crabs-live.md
.changeset/pink-oranges-attack.md
.changeset/pink-planes-wait.md
.changeset/sixty-carrots-sniff.md
.changeset/young-worms-repair.md
packages/assets/CHANGELOG.md
packages/assets/package.json
packages/icons/CHANGELOG.md
packages/icons/package.json
packages/solana/CHANGELOG.md
packages/solana/package.json
packages/wagmi/CHANGELOG.md
packages/wagmi/package.json
packages/web3/CHANGELOG.md
packages/web3/package.json

🦋  @ant-design/web3-assets@1.4.0
🦋  @ant-design/web3-icons@1.4.0
🦋  @ant-design/web3-solana@0.1.2
🦋  @ant-design/web3-wagmi@2.3.0
🦋  @ant-design/web3@1.7.2

chore: release 1.7.2

---

.changeset/hot-impalas-pretend.md
packages/web3/src/connect-modal/style/index.tsx

fix: panel borderRadius

---

.changeset/hot-impalas-pretend.md

chore: fire redundant changeset

---

.changeset/four-teachers-doubt.md
packages/web3/src/connect-modal/style/index.tsx

feat: remove connect modal overflow

---

packages/wagmi/src/wagmi-provider/__tests__/basic.test.tsx

chore: fix ci issue

---

.changeset/sweet-carpets-walk.md
packages/solana/src/solana-provider/__tests__/basic.test.tsx
packages/solana/src/solana-provider/__tests__/switch-chain.test.tsx
packages/solana/src/solana-provider/config-provider.tsx
packages/solana/src/solana-provider/index.tsx
packages/web3/src/solana/demos/networks.tsx
packages/web3/src/solana/index.md
packages/web3/src/solana/index.zh-CN.md

feat(solana): Simplify solana provider properties, remove `chainAssets`

---

.changeset/shy-dancers-drop.md
packages/wagmi/src/wagmi-provider/__tests__/config-with-eip6963-and-wallets.test.tsx
packages/wagmi/src/wagmi-provider/__tests__/config-with-eip6963-wallet.test.tsx
packages/web3/src/connect-modal/__tests__/__snapshots__/basic.test.tsx.snap
packages/web3/src/connect-modal/__tests__/__snapshots__/simple.test.tsx.snap
packages/web3/src/connect-modal/components/WalletList.tsx
packages/web3/src/connect-modal/style/index.tsx

fix: wallet icon display error in eip6963 mode

---

.dumi/theme/builtins/HomePage/components/Theme/index.module.less
.dumi/theme/builtins/HomePage/components/Theme/index.tsx

fix: ConnectModal style in index page demo

---

.changeset/early-bugs-help.md
packages/wagmi/src/wagmi-provider/__tests__/ens.test.tsx
packages/wagmi/src/wagmi-provider/config-provider.tsx

fix: The button status is incorrect when requesting ENS information

---

.changeset/early-bugs-help.md
.changeset/five-frogs-refuse.md
.changeset/four-teachers-doubt.md
.changeset/happy-penguins-taste.md
.changeset/little-cougars-smile.md
.changeset/polite-wasps-beam.md
.changeset/shy-dancers-drop.md
.changeset/six-toys-burn.md
.changeset/sour-trains-happen.md
.changeset/sweet-carpets-walk.md
packages/assets/CHANGELOG.md
packages/assets/package.json
packages/common/CHANGELOG.md
packages/common/package.json
packages/icons/CHANGELOG.md
packages/icons/package.json
packages/solana/CHANGELOG.md
packages/solana/package.json
packages/wagmi/CHANGELOG.md
packages/wagmi/package.json
packages/web3/CHANGELOG.md
packages/web3/package.json

Success packages published successfully:
🦋  @ant-design/web3-assets@1.4.1
🦋  @ant-design/web3-common@1.6.0
🦋  @ant-design/web3-icons@1.4.1
🦋  @ant-design/web3-solana@1.0.0
🦋  @ant-design/web3-wagmi@2.4.0
🦋  @ant-design/web3@1.8.0

chore: release 1.8.0 & solana 1.0.0

---

.changeset/olive-numbers-march.md
packages/wagmi/src/wagmi-provider/__tests__/nft.test.tsx
packages/web3/src/nft-card/NFTCard.tsx
packages/web3/src/nft-card/__tests__/action.test.tsx
packages/web3/src/nft-card/__tests__/basic.test.tsx
packages/web3/src/nft-card/__tests__/like.test.tsx

chore: modify NFTCard className prefix

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE/pr_cn.md

https://github.com/ant-design/ant-design-web3/community

feat: Improve community configuration

---

README.md

fix: remove -cn for fix get start link in readme

---

.github/workflows/release-tweet.yml

替换了一下 @ 符号
🤖 Ant Design Web3 just released @​ant-design/web3@1.7.0 ✨🎊✨ Check out the full release note: https://github.com/ant-design/ant-design-web3/releases/tag/@ant-design/web3@1.7.0
测试了一下效果，目前不会提及无关人员

ci(tweet): avoid mentioning irrelevant people

---

docs/guide/demos/guide.tsx

docs: update demo in guide, add quickConnect to ConnectButton

---

.dumirc.ts
docs/course/dev-call-contract.md
docs/course/dev-call-contract.zh-CN.md
docs/course/intro-call-contract.md
docs/course/intro-call-contract.zh-CN.md
docs/course/intro-dapp.md
docs/course/intro-dapp.zh-CN.md
packages/web3/src/wagmi/demos/uiconfig.tsx

docs: add chInfo for zan.top

---

.changeset/cool-apes-rule.md
.changeset/hot-cheetahs-cheat.md
.changeset/olive-numbers-march.md
.changeset/sharp-seas-bow.md
.changeset/smooth-trees-stare.md
packages/assets/CHANGELOG.md
packages/assets/package.json
packages/common/CHANGELOG.md
packages/common/package.json
packages/icons/CHANGELOG.md
packages/icons/package.json
packages/solana/CHANGELOG.md
packages/solana/package.json
packages/wagmi/CHANGELOG.md
packages/wagmi/package.json
packages/web3/CHANGELOG.md
packages/web3/package.json

🦋  @ant-design/web3-assets@1.5.0
🦋  @ant-design/web3-common@1.7.0
🦋  @ant-design/web3-icons@1.4.2
🦋  @ant-design/web3-solana@1.0.1
🦋  @ant-design/web3-wagmi@2.4.1
🦋  @ant-design/web3@1.9.0

chore(release): web3 1.9.0 wagmi 2.4.1 and solana 1.0.1

---

.github/workflows/release-dingtalk.yml
.github/workflows/release-tweet.yml

@thinkasany 两个发布通知的 ci 都被 skip 了

chore(ci): use release publish event instead

---

docs/guide/contributing.md
docs/guide/contributing.zh-CN.md

docs: update docs about tag

---

docs/guide/demos/custom-token.tsx
docs/guide/demos/theme.tsx

docs: update custom theme demo width

---

package.json
packages/web3/package.json
packages/web3/src/address/__tests__/__snapshots__/index.test.tsx.snap
packages/web3/src/connect-button/__tests__/__snapshots__/profile-modal.test.tsx.snap
packages/web3/src/connect-button/__tests__/__snapshots__/tooltip.test.tsx.snap
packages/web3/src/connect-modal/__tests__/__snapshots__/basic.test.tsx.snap
packages/web3/src/connect-modal/__tests__/__snapshots__/simple.test.tsx.snap
packages/web3/src/nft-image/__tests__/__snapshots__/index.test.tsx.snap
packages/web3/src/web3-config-provider/__tests__/__snapshots__/index.test.tsx.snap
pnpm-lock.yaml

#679 需要新版本的antd的qrcode组件来修复这个bug

chore: upgrade antd to 5.15.4 & cssinjs to 1.18.5

---

README-zh_CN.md
README.md

docs: img add default alt

---

.dumirc.ts

docs: update footer, add Partners

---

README-zh_CN.md
README.md

Readme 中的 star history chart 兼容暗色模式

docs(workspace): update star-history chart

---

.changeset/shaggy-snakes-play.md
packages/web3/src/connect-modal/components/WalletCard.tsx

fix: add default alt attribute to img

---

.changeset/shiny-stingrays-notice.md
packages/web3/src/connect-modal/components/DefaultGuidePanel.tsx

chore: optimize code

---

.github/workflows/issue-labeled.yml

ci: Issue Labeled

---

.changeset/pretty-ducks-hide.md
docs/guide/ant-design-web3.md
docs/guide/ant-design-web3.zh-CN.md
packages/web3/src/connect-button/connect-button-inner.tsx
packages/web3/src/connect-modal/components/WalletCard.tsx

style: format code

---

.dumi/theme/builtins/HomePage/components/Banner/index.module.less
.dumi/theme/builtins/HomePage/components/Banner/index.tsx

feat: optimize banner style in dark theme

---

.github/PULL_REQUEST_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE/pr_cn.md

chore: update pr template

---

package.json
pnpm-lock.yaml

左侧logo把容器撑高了
dumi-theme-antd-web3@0.3.13 中修复了这个bug，通过升级解决了此问题
fix #722

fix:website logo height overflow #722

---

package.json
pnpm-lock.yaml

site: fix some site issue

---

.changeset/poor-bugs-promise.md
packages/web3/src/browser-link/__tests__/anchor.test.tsx
packages/web3/src/browser-link/demos/basic.tsx
packages/web3/src/browser-link/demos/complex.tsx
packages/web3/src/browser-link/demos/customName.tsx
packages/web3/src/browser-link/demos/icononly.tsx
packages/web3/src/browser-link/index.tsx
packages/web3/src/connect-modal/components/PluginTag.tsx
packages/web3/src/connector/connector.tsx

feat(comp): BrowerLink props extend anchor element

---

packages/web3/src/types/index.md
packages/web3/src/types/index.zh-CN.md
packages/web3/src/web3-config-provider/index.md
packages/web3/src/web3-config-provider/index.zh-CN.md

fix Web3ConfigProvider API docs type link bug

docs: fix Web3ConfigProvider API type link bug

---

docs/guide/contributing.md
docs/guide/contributing.zh-CN.md

chore: add 'Need Changelog' label introduce

---

.changeset/fair-meals-whisper.md
packages/web3/src/nft-card/NFTCard.tsx

 refactor:optimize nft-card conditinal render

---

.changeset/gold-jeans-care.md
packages/web3/src/connect-button/connect-button.tsx
packages/web3/src/connect-modal/__tests__/pluginTag.test.tsx

fix: optimize import type

---

.changeset/small-eyes-add.md
.dumi/theme/builtins/IconSearch/Category.tsx
packages/web3/src/connect-button/connect-button.tsx

chore(category): use contextHolder

---

.prettierignore

chore(prettier): ignore changeset

---

.dumi/theme/builtins/HomePage/components/Theme/index.module.less

site: dark theme opt

---

.changeset/fifty-crabs-retire.md
packages/web3/src/connect-modal/components/PluginTag.tsx
packages/web3/src/connect-modal/style/index.tsx

feat: optimize plugin tag token in ConnectModal

---

docs/guide/contributing.md
docs/guide/contributing.zh-CN.md

docs: opt docs

---

packages/web3/src/solana/index.zh-CN.md

docs: Update solana/index.zh-CN.md

---

.dumi/global.less

site: site opt

---

.dumi/theme/builtins/NormalCommand/index.tsx
.github/workflows/pr-labeled.yml
docs/guide/changelog.md
docs/guide/changelog.zh-CN.md

更详细的指引，通过label自动贴上指南，告诉用户什么情况下需要生成changelog以及生成changlog需要了解的注意事项

docs: guide for changelog

---

.changeset/lucky-kiwis-relate.md
package.json
packages/icons/package.json
packages/web3/package.json
pnpm-lock.yaml

chore: upgrade @ant-design/icons to 5.3.6

---

docs/guide/contribute-icons.md
docs/guide/contribute-icons.zh-CN.md

docs: opt How to Contribute Icons

---

.github/workflows/pr-contributor-welcome.yml

增加限制条件 跳过dependabot[bot]，避免依赖升级时的报错

chore(contributor-welcome): skip dependabot[bot]

---

.changeset/cuddly-mugs-compete.md
packages/solana/src/solana-provider/index.tsx
packages/solana/src/utils.ts

fix: update typo from isWalletConnnectFactory to isWalletConnectFactory

---

biome.json

fix wrong biome schema address

chore: fix biomejs schema address

---

.changeset/pretty-moons-itch.md
packages/web3/src/connect-modal/style/index.tsx

fix: fix ConnectModal style issue in dark mode

---

.changeset/warm-cameras-taste.md
packages/solana/src/solana-provider/__tests__/connect.test.tsx
packages/solana/src/solana-provider/__tests__/standard-wallet.test.tsx
packages/solana/src/solana-provider/config-provider.tsx
packages/solana/src/solana-provider/index.tsx
packages/solana/src/utils.ts
packages/solana/src/wallets/built-in.ts
packages/solana/src/wallets/factory.ts
packages/solana/src/wallets/types.ts

- feat: add Standard Wallet support
- feat: add `OKXWallet` (closed #750 )
- refactor: change `PhantomWallet` to Standard Wallet

feat(solana): Support standard wallets

---

.github/workflows/pr-labeled.yml

预留一个自动评论，因为可能很多用户会来提交icon的pr，方便发送提示词。

ci(pr-labeled): Generate Icons

---

docs/guide/adapter.zh-CN.md

docs: Update adapter.zh-CN.md

---

.changeset/blue-kids-rhyme.md
.dumi/theme/builtins/HomePage/components/Theme/index.tsx
.dumi/theme/layouts/GlobalLayout.tsx
packages/web3/src/connect-modal/components/GetWalletPanel.tsx
packages/web3/src/connect-modal/demos/theme.tsx
packages/web3/src/connect-modal/style/index.tsx

refactor: optimize connect-modal's token

---

.dumi/global.less

docs: set scroll margin to doc site

---

.changeset/good-rabbits-draw.md
packages/web3/src/crypto-price/__tests__/basic.test.tsx
packages/web3/src/crypto-price/balance.tsx
packages/web3/src/crypto-price/demos/format.tsx
packages/web3/src/crypto-price/index.md
packages/web3/src/crypto-price/index.tsx
packages/web3/src/crypto-price/index.zh-CN.md

feat: crypto-price support custom format

---

.github/workflows/build.yml
.github/workflows/test.yml

ci: lock pnpm@8.9.0 version

---

.dumi/theme/layouts/GlobalLayout.tsx
packages/web3/src/connect-modal/__tests__/__snapshots__/basic.test.tsx.snap
packages/web3/src/connect-modal/__tests__/basic.test.tsx
tsconfig.base.json

fix: issues before release

---

.changeset/selfish-bananas-juggle.md
packages/assets/src/chains/ethereum.tsx
packages/common/src/types.ts
packages/web3/src/ethereum/demos/chains.tsx

新增 Hardhat 和 Localhost 两条本地用的测试链，方便开发调试。

feat: Add test chain hardhat and localhost

---

.dumirc.ts

site: hide docVersions

---

packages/web3/src/connect-modal/components/ModalPanel.tsx
packages/web3/src/connect-modal/interface.ts

chore: remove 'getWallet' panelRoute

---

.changeset/quiet-pumas-drive.md
packages/web3/src/connect-modal/style/index.tsx

refactor: remove unused code

---

.changeset/ninety-emus-pull.md
packages/solana/src/solana-provider/__tests__/basic.test.tsx
packages/solana/src/solana-provider/__tests__/switch-chain.test.tsx
packages/solana/src/solana-provider/index.tsx

feat(solana): Get default chain from 'chains'

---

.prettierrc

解决 Prettier 格式化删除必要的 React 的问题
https://github.com/simonhaenisch/prettier-plugin-organize-imports?tab=readme-ov-file#skip-destructive-code-actions
- #845

chore: update .prettierrc

---

.changeset/plenty-islands-protect.md
package.json
packages/web3/package.json
packages/web3/src/address/__tests__/__snapshots__/index.test.tsx.snap
packages/web3/src/connect-button/__tests__/__snapshots__/profile-modal.test.tsx.snap
packages/web3/src/connect-button/__tests__/__snapshots__/tooltip.test.tsx.snap
packages/web3/src/connect-modal/__tests__/__snapshots__/basic.test.tsx.snap
packages/web3/src/connect-modal/__tests__/__snapshots__/simple.test.tsx.snap
packages/web3/src/nft-image/__tests__/__snapshots__/index.test.tsx.snap
packages/web3/src/web3-config-provider/__tests__/__snapshots__/index.test.tsx.snap
pnpm-lock.yaml

5.17修复 QRCode 无法自适应容器大小的问题
#679

chore: upgrade antd to 5.17.0 & cssinjs to 1.20.0

---

.changeset/ten-suns-love.md
packages/wagmi/src/wallets/__tests__/wallet-connect.test.tsx
packages/web3/src/connect-modal/__tests__/__snapshots__/basic.test.tsx.snap
packages/web3/src/connect-modal/components/QrCode.tsx
packages/web3/src/connect-modal/context/index.ts
packages/web3/src/nft-card/__tests__/basic.test.tsx

修复窗口比较小的时候二维码可能会溢出，保障尽量的适应屏幕宽度
close #679

fix: ConnectModal QRCode overflow

---

packages/web3/src/types/index.md
packages/web3/src/types/index.zh-CN.md

docs: add Wallet hasExtensionInstalled for type doc

---

.changeset/poor-dragons-approve.md
packages/icons/package.json

perf(icons): add 'sideEffects' for Tree shaking

---

package.json
packages/ethers/package.json
packages/wagmi/package.json
pnpm-lock.yaml

几个构建问题：
1. #836 中升级 dumi 后，导出缺少了 `useIntl` 和 `usePrefersColor`，没找到 changelog，暂时回退版本发布
2. wagmi、wagmi core、viem 的 semver 小版本不对应，导致 ts 类型错误：Closes #854 Closes #856

fix(workspace): build and ci issues

---

docs/guide/ant-design-web3.md
docs/guide/ant-design-web3.zh-CN.md

docs: update Why use ant design web3, add Bitcoin

---

packages/assets/CHANGELOG.md
packages/common/CHANGELOG.md
packages/icons/CHANGELOG.md

docs: opt typo

---

.changeset/cool-windows-float.md
packages/web3/src/address/index.tsx

refactor(address): copyable prop default is false

---

.changeset/rude-apples-chew.md
docs/guide/quick-start.md
docs/guide/quick-start.zh-CN.md
packages/bitcoin/package.json
packages/bitcoin/src/error.ts
packages/bitcoin/src/helpers.tsx
packages/bitcoin/src/provider/__tests__/basic.test.tsx
packages/bitcoin/src/wallets/factory.ts
packages/bitcoin/src/wallets/index.ts
packages/bitcoin/src/wallets/types.ts
pnpm-lock.yaml

适配 Next.js，包括：
https://github.com/ant-design/ant-design-web3/issues/880
https://github.com/ant-design/ant-design-web3/issues/878

fix(bitcoin): adapt to Next.js

---

.changeset/famous-pugs-explain.md
packages/web3/src/connect-button/__tests__/chains.test.tsx
packages/web3/src/connect-button/chain-select.tsx
packages/web3/src/connect-button/connect-button.tsx
packages/web3/src/connect-button/demos/chains.tsx

 fix: chain select style bug when ConnectButton set type or size

---

.changeset/famous-pugs-explain.md
.changeset/little-weeks-hug.md
examples/eth-web3js/CHANGELOG.md
examples/eth-web3js/package.json
examples/ethers-v5/CHANGELOG.md
examples/ethers-v5/package.json
examples/ethers/CHANGELOG.md
examples/ethers/package.json
packages/solana/CHANGELOG.md
packages/solana/package.json
packages/web3/CHANGELOG.md
packages/web3/package.json

🦋  @ant-design/web3-solana@1.1.3
🦋  @ant-design/web3@1.11.2

release: web3 v1.11.2

---

.changeset/moody-moons-hug.md
packages/bitcoin/src/adapter/wallets/index.ts
packages/bitcoin/src/adapter/wallets/okx.ts
packages/bitcoin/src/global.d.ts
packages/bitcoin/src/wallets/index.ts
packages/web3/src/bitcoin/demos/basic.tsx
packages/web3/src/bitcoin/demos/send-transfer.tsx
packages/web3/src/bitcoin/demos/sign.tsx
packages/web3/src/bitcoin/index.md
packages/web3/src/bitcoin/index.zh-CN.md

feat: add bitcoin okx wallet

---

packages/web3/src/solana/demos/balance.tsx
packages/web3/src/solana/demos/basic.tsx
packages/web3/src/solana/demos/more-wallets.tsx
packages/web3/src/solana/demos/networks.tsx
packages/web3/src/solana/demos/sign-message.tsx
packages/web3/src/solana/demos/wallet-connect.tsx

去掉 Solana demo 中的 `autoConnect` 配置，避免偶尔会出现打开此页面时，频繁弹出钱包插件的问题。

docs: remove 'autoConnect' on solana demos

---

.changeset/bright-pugs-glow.md
.changeset/brown-eyes-deny.md
.changeset/moody-moons-hug.md
.changeset/yellow-cameras-know.md
examples/eth-web3js/CHANGELOG.md
examples/eth-web3js/package.json
examples/ethers-v5/CHANGELOG.md
examples/ethers-v5/package.json
examples/ethers/CHANGELOG.md
examples/ethers/package.json
packages/assets/CHANGELOG.md
packages/assets/package.json
packages/bitcoin/CHANGELOG.md
packages/bitcoin/package.json
packages/common/CHANGELOG.md
packages/common/package.json
packages/eth-web3js/CHANGELOG.md
packages/eth-web3js/package.json
packages/ethers-v5/CHANGELOG.md
packages/ethers-v5/package.json
packages/ethers/CHANGELOG.md
packages/ethers/package.json
packages/solana/CHANGELOG.md
packages/solana/package.json
packages/wagmi/CHANGELOG.md
packages/wagmi/package.json
packages/web3/CHANGELOG.md
packages/web3/package.json

🦋  @ant-design/web3-assets@1.7.2
🦋  @ant-design/web3-bitcoin@1.2.0
🦋  @ant-design/web3-common@1.10.0
🦋  @ant-design/web3-eth-web3js@1.1.0
🦋  @ant-design/web3-ethers@1.1.0
🦋  @ant-design/web3-ethers-v5@1.0.1
🦋  @ant-design/web3-solana@1.1.4
🦋  @ant-design/web3-wagmi@2.4.5
🦋  @ant-design/web3@1.12.0

release: 1.12.0

---

docs/meetup2024/dapp.tsx
docs/meetup2024/index.md
docs/meetup2024/mint.tsx
docs/meetup2024/sbt.tsx

给参加 Ant Design 2024 meetup 现场的同学发放 sbt nft

feat: add ant design meetup 2024 sbt dapp

---

docs/guide/demos/guide.tsx

docs: improve demo in guide

---

docs/meetup2024/dapp.tsx
docs/meetup2024/mint.tsx
docs/meetup2024/sbt.tsx

mint 的时候需要等待较长时间，添加 loading 效果。

fix: add loading to mint button

---

.changeset/clean-badgers-invite.md
docs/guide/demos/custom-token.tsx
packages/web3/src/connect-modal/components/QrCode.tsx
packages/web3/src/connect-modal/style/index.tsx

fix: modal connect wallet vertical align & overflow

---

.changeset/good-numbers-lick.md
packages/web3/src/connect-modal/__tests__/__snapshots__/basic.test.tsx.snap
packages/web3/src/connect-modal/__tests__/__snapshots__/simple.test.tsx.snap
packages/web3/src/connect-modal/components/ModalPanel.tsx
packages/web3/src/connect-modal/style/index.tsx
packages/web3/src/ethereum/demos/more-wallets-in-simple.tsx
packages/web3/src/ethereum/index.md
packages/web3/src/ethereum/index.zh-CN.md

限制一下最大高度，避免钱包太多时候被撑开
https://github.com/ant-design/ant-design-web3/pull/920#issuecomment-2141381787

fix: wallets container height style

---

docs/guide/demos/guide.tsx

Demo 添加切换样式示例，后续需要持续补充更多样式以及完善该 Demo 样式

docs: support select theme in try it out demo

---

.github/dependabot.yml

chore: ignore dumi upgrade

---

.dumi/theme/builtins/HomePage/components/Banner/index.module.less
.dumi/theme/builtins/HomePage/components/Banner/index.tsx
.dumi/theme/builtins/HomePage/components/Features/index.module.less
.dumi/theme/builtins/HomePage/components/Features/index.tsx
.dumi/theme/builtins/HomePage/components/ShowCase/index.module.less
.dumi/theme/builtins/HomePage/components/ShowCase/index.tsx
.dumi/theme/builtins/HomePage/components/Theme/index.module.less
.dumi/theme/builtins/HomePage/components/Theme/index.tsx
.dumi/theme/builtins/HomePage/index.module.less
.dumi/theme/builtins/HomePage/index.tsx

site: optimize site home page

---

.dumi/theme/builtins/HomePage/components/Banner/index.module.less
.dumi/theme/builtins/HomePage/components/Banner/index.tsx
.dumi/theme/builtins/HomePage/components/Features/index.module.less
.dumi/theme/builtins/HomePage/components/Features/index.tsx
.dumi/theme/builtins/HomePage/components/ShowCase/index.module.less
.dumi/theme/builtins/HomePage/components/Theme/index.module.less

site: fix some ui details

---

.changeset/yellow-ants-perform.md
packages/wagmi/package.json
packages/wagmi/src/wagmi-provider/__tests__/balance.test.tsx
packages/wagmi/src/wagmi-provider/__tests__/connect-with-universal-wallet.test.tsx
packages/wagmi/src/wagmi-provider/__tests__/connect.test.tsx
packages/wagmi/src/wagmi-provider/__tests__/ens.test.tsx
packages/wagmi/src/wagmi-provider/__tests__/nft.test.tsx
packages/wagmi/src/wagmi-provider/__tests__/switch-chain-unconnected.test.tsx
packages/wagmi/src/wagmi-provider/__tests__/switch-chain.test.tsx
packages/wagmi/src/wagmi-provider/__tests__/unconnected.test.tsx
packages/wagmi/src/wagmi-provider/config-provider.tsx
packages/wagmi/src/wagmi-provider/methods/getNFTMetadata.ts
pnpm-lock.yaml

剔除了对 `@wagmi/core` 的直接依赖，改用 `wagmi/actions`，dependbot 的那个问题也应该一并解决了 cc @thinkasany

chore(wagmi): use wagmi/actions instead of wagmi/core

---

.changeset/cuddly-countries-deliver.md
.changeset/good-numbers-lick.md
.changeset/long-students-impress.md
.changeset/serious-ducks-jog.md
.changeset/tiny-hotels-peel.md
.changeset/yellow-ants-perform.md
examples/eth-web3js/CHANGELOG.md
examples/eth-web3js/package.json
examples/ethers-v5/CHANGELOG.md
examples/ethers-v5/package.json
examples/ethers/CHANGELOG.md
examples/ethers/package.json
packages/assets/CHANGELOG.md
packages/assets/package.json
packages/bitcoin/CHANGELOG.md
packages/bitcoin/package.json
packages/common/CHANGELOG.md
packages/common/package.json
packages/eth-web3js/CHANGELOG.md
packages/eth-web3js/package.json
packages/ethers-v5/CHANGELOG.md
packages/ethers-v5/package.json
packages/ethers/CHANGELOG.md
packages/ethers/package.json
packages/solana/CHANGELOG.md
packages/solana/package.json
packages/wagmi/CHANGELOG.md
packages/wagmi/package.json
packages/web3/CHANGELOG.md
packages/web3/package.json

🦋  @ant-design/web3-assets@1.8.1
🦋  @ant-design/web3-bitcoin@1.3.1
🦋  @ant-design/web3-common@1.11.0
🦋  @ant-design/web3-eth-web3js@1.1.2
🦋  @ant-design/web3-ethers@1.1.2
🦋  @ant-design/web3-ethers-v5@1.0.3
🦋  @ant-design/web3-solana@1.1.6
🦋  @ant-design/web3-wagmi@2.6.0
🦋  @ant-design/web3@1.14.0

release: v1.14.0

---

docs/course/advanced-more.md
packages/assets/package.json
packages/common/package.json
packages/eth-web3js/package.json
packages/ethers-v5/package.json
packages/ethers/package.json
packages/icons/package.json
packages/wagmi/package.json
packages/web3/package.json

chore: fix typo

---

package.json
pnpm-lock.yaml

fix(docs): language switcher not working as expected in mobile mode

---

.changeset/honest-pumpkins-act.md
packages/common/src/types.ts
packages/wagmi/src/wagmi-provider/__tests__/balance.test.tsx
packages/wagmi/src/wagmi-provider/__tests__/config-with-eip6963-and-wallets.test.tsx
packages/wagmi/src/wagmi-provider/__tests__/connect-with-universal-wallet.test.tsx
packages/wagmi/src/wagmi-provider/__tests__/connect.test.tsx
packages/wagmi/src/wagmi-provider/__tests__/ens.test.tsx
packages/wagmi/src/wagmi-provider/__tests__/nft.test.tsx
packages/wagmi/src/wagmi-provider/__tests__/switch-chain-unconnected.test.tsx
packages/wagmi/src/wagmi-provider/__tests__/switch-chain.test.tsx
packages/wagmi/src/wagmi-provider/__tests__/unconnected.test.tsx
packages/wagmi/src/wagmi-provider/config-provider.tsx
packages/web3/src/connect-button/connect-button.tsx

feat(connector): auto display ens avatar

---

.changeset/blue-rats-sort.md
.changeset/honest-pumpkins-act.md
.changeset/lucky-toes-film.md
.changeset/tender-clouds-applaud.md
.changeset/tidy-dodos-grin.md
examples/eth-web3js/CHANGELOG.md
examples/eth-web3js/package.json
examples/ethers-v5/CHANGELOG.md
examples/ethers-v5/package.json
examples/ethers/CHANGELOG.md
examples/ethers/package.json
packages/assets/CHANGELOG.md
packages/assets/package.json
packages/bitcoin/CHANGELOG.md
packages/bitcoin/package.json
packages/common/CHANGELOG.md
packages/common/package.json
packages/eth-web3js/CHANGELOG.md
packages/eth-web3js/package.json
packages/ethers-v5/CHANGELOG.md
packages/ethers-v5/package.json
packages/ethers/CHANGELOG.md
packages/ethers/package.json
packages/solana/CHANGELOG.md
packages/solana/package.json
packages/wagmi/CHANGELOG.md
packages/wagmi/package.json
packages/web3/CHANGELOG.md
packages/web3/package.json

🦋  @ant-design/web3-assets@1.9.0
🦋  @ant-design/web3-bitcoin@1.4.0
🦋  @ant-design/web3-common@1.12.0
🦋  @ant-design/web3-eth-web3js@1.1.3
🦋  @ant-design/web3-ethers@1.1.3
🦋  @ant-design/web3-ethers-v5@1.0.4
🦋  @ant-design/web3-solana@1.1.7
🦋  @ant-design/web3-wagmi@2.7.0
🦋  @ant-design/web3@1.15.0

release: 1.15.0

---

.changeset/lovely-horses-obey.md
examples/eth-web3js/CHANGELOG.md
examples/eth-web3js/package.json
examples/ethers-v5/CHANGELOG.md
examples/ethers-v5/package.json
examples/ethers/CHANGELOG.md
examples/ethers/package.json
packages/web3/CHANGELOG.md
packages/web3/package.json

release: v1.15.1

---

.dumi/theme/builtins/HomePage/components/Features/index.module.less

`white-space` 好像没有 `warp` 属性所以移动端换行失效了。
https://developer.mozilla.org/en-US/docs/Web/CSS/white-space
close #966

site(mobile): fix white-space

---

.changeset/sour-boats-flow.md
packages/web3/src/crypto-input/index.tsx
packages/web3/src/crypto-input/style/index.ts

纠错一下上一个pr修改忘记改style token这边导致样式丢失 #1004 ，thanks for @gin-lsl review。

fix(crypto-input): fix token style

---

package.json
pnpm-lock.yaml

chore(bump): upgrade dumi-theme-antd-web3 to 0.4.2

---

.changeset/moody-beers-dream.md
packages/web3/src/connect-button/style/index.ts

fix: ConnectButton text color with primary type

---

packages/web3/src/pay-panel/index.md
packages/web3/src/pay-panel/index.zh-CN.md

docs: typo

---

.changeset/green-teachers-bow.md
packages/assets/src/tokens/eth.tsx
packages/assets/src/tokens/index.ts
packages/assets/src/tokens/usdc.tsx
packages/assets/src/tokens/usdt.tsx
packages/web3/src/crypto-input/demos/basic.tsx

数据来源：https://developers.circle.com/stablecoins/docs/usdc-on-main-networks

feat(assets): Add USDC token

---

.dumi/theme/common/styles/Icon.tsx

style(site): fix icons label overflow

---

packages/web3/src/web3-config-provider/demos/basic.tsx
packages/web3/src/web3-config-provider/demos/custom-adapter.tsx
packages/web3/src/web3-config-provider/index.md
packages/web3/src/web3-config-provider/index.zh-CN.md

之前的 Demo 有问题，修复了一下。另外拆分为了两个 Demo。

docs: update Web3ConfigProvider demos

---

package.json
pnpm-lock.yaml

feat(site): support toggleAnimationTheme

---

docs/guide/ant-design-web3.md
docs/guide/ant-design-web3.zh-CN.md

docs: add TON support in intro doc

---

packages/web3/src/pay-panel/index.zh-CN.md

feat: optimize overview

---

.changeset/early-bags-shave.md
packages/ton/src/wallets/okxTonWallet.tsx
packages/ton/src/wallets/type.ts

修改 TonOkxWallet 的 metadata
#1071

fix: update okx wallet info in ton provider

---

packages/web3/src/connect-button/index.zh-CN.md
packages/web3/src/connect-modal/index.zh-CN.md
packages/web3/src/connector/index.zh-CN.md

docs: fix typo for connect

---

.changeset/fifty-pans-tease.md
.changeset/moody-elephants-talk.md
examples/eth-web3js/CHANGELOG.md
examples/eth-web3js/package.json
examples/ethers-v5/CHANGELOG.md
examples/ethers-v5/package.json
examples/ethers/CHANGELOG.md
examples/ethers/package.json
packages/eth-web3js/CHANGELOG.md
packages/eth-web3js/package.json
packages/ethers-v5/CHANGELOG.md
packages/ethers-v5/package.json
packages/ethers/CHANGELOG.md
packages/ethers/package.json
packages/wagmi/CHANGELOG.md
packages/wagmi/package.json

🦋  success packages published successfully:
🦋  @ant-design/web3-eth-web3js@1.1.6
🦋  @ant-design/web3-ethers@1.1.6
🦋  @ant-design/web3-ethers-v5@1.0.7
🦋  @ant-design/web3-wagmi@2.7.3

chore: release @ant-design/web3-wagmi@2.7.3

---

.changeset/blue-games-happen.md
.changeset/hip-comics-invite.md
examples/eth-web3js/CHANGELOG.md
examples/eth-web3js/package.json
examples/ethers-v5/CHANGELOG.md
examples/ethers-v5/package.json
examples/ethers/CHANGELOG.md
examples/ethers/package.json
packages/assets/CHANGELOG.md
packages/assets/package.json
packages/bitcoin/CHANGELOG.md
packages/bitcoin/package.json
packages/common/CHANGELOG.md
packages/common/package.json
packages/eth-web3js/CHANGELOG.md
packages/eth-web3js/package.json
packages/ethers-v5/CHANGELOG.md
packages/ethers-v5/package.json
packages/ethers/CHANGELOG.md
packages/ethers/package.json
packages/solana/CHANGELOG.md
packages/solana/package.json
packages/sui/CHANGELOG.md
packages/sui/package.json
packages/ton/CHANGELOG.md
packages/ton/package.json
packages/wagmi/CHANGELOG.md
packages/wagmi/package.json
packages/web3/CHANGELOG.md
packages/web3/package.json

🦋  success packages published successfully:
🦋  @ant-design/web3-assets@1.10.2
🦋  @ant-design/web3-bitcoin@1.4.3
🦋  @ant-design/web3-common@1.13.0
🦋  @ant-design/web3-eth-web3js@1.1.7
🦋  @ant-design/web3-ethers@1.1.7
🦋  @ant-design/web3-ethers-v5@1.0.8
🦋  @ant-design/web3-solana@1.1.10
🦋  @ant-design/web3-sui@1.0.0
🦋  @ant-design/web3-ton@1.0.2
🦋  @ant-design/web3-wagmi@2.7.4
🦋  @ant-design/web3@1.16.2

chore: release @ant-design/web3-sui@1.0.0

---

packages/web3/src/pay-panel/demos/basic.tsx
packages/web3/src/pay-panel/demos/useGasRender.tsx

site: import react in demos

---

docs/guide/demos/guide.module.less

问题来自于这边，dark模式的时候也显示了这个白色
https://github.com/ant-design/ant-design-web3/pull/1031/files#diff-af695945508383dfe144f45e21777064d77a86b72855098465b575d5c832f4b4R8
close #1120

fix(site):  demo style bug in dark mode

---

.dumi/theme/builtins/HomePage/components/ShowCase/CryptoInput.tsx

fix: 修复暗色背景按钮字符颜色异常问题

---

.dumirc.ts

docs: add Telegram group

---

.changeset/healthy-spies-smash.md
packages/solana/src/solana-provider/__tests__/connect.test.tsx
packages/solana/src/solana-provider/config-provider.tsx
packages/sui/src/sui-provider/config-provider.tsx
packages/web3/src/solana/demos/balance.tsx
packages/web3/src/solana/demos/basic.tsx
packages/web3/src/solana/demos/more-components.tsx
packages/web3/src/solana/demos/more-wallets.tsx
packages/web3/src/solana/demos/networks.tsx
packages/web3/src/solana/demos/sign-message.tsx
packages/web3/src/solana/demos/wallet-connect.tsx

fix(sui,solana): Should return address after connect

---

.changeset/fuzzy-singers-search.md
.changeset/healthy-spies-smash.md
.changeset/wise-dodos-juggle.md
examples/eth-web3js/CHANGELOG.md
examples/eth-web3js/package.json
examples/ethers-v5/CHANGELOG.md
examples/ethers-v5/package.json
examples/ethers/CHANGELOG.md
examples/ethers/package.json
packages/assets/CHANGELOG.md
packages/assets/package.json
packages/eth-web3js/CHANGELOG.md
packages/eth-web3js/package.json
packages/ethers-v5/CHANGELOG.md
packages/ethers-v5/package.json
packages/ethers/CHANGELOG.md
packages/ethers/package.json
packages/solana/CHANGELOG.md
packages/solana/package.json
packages/sui/CHANGELOG.md
packages/sui/package.json
packages/ton/CHANGELOG.md
packages/ton/package.json
packages/wagmi/CHANGELOG.md
packages/wagmi/package.json
packages/web3/CHANGELOG.md
packages/web3/package.json

🦋  success packages published successfully:
🦋  @ant-design/web3-assets@1.11.0
🦋  @ant-design/web3-eth-web3js@1.1.8
🦋  @ant-design/web3-ethers@1.1.8
🦋  @ant-design/web3-ethers-v5@1.0.9
🦋  @ant-design/web3-solana@1.1.11
🦋  @ant-design/web3-sui@1.0.1
🦋  @ant-design/web3-ton@1.0.3
🦋  @ant-design/web3-wagmi@2.8.0
🦋  @ant-design/web3@1.16.3

chore: release @ant-design/web3-wagmi 2.8.0

---

packages/web3/src/ethereum/index.md

docs: add version note for wagmi config

---

.dumi/theme/builtins/IconSearch/IconSearch.tsx
.dumi/theme/locales/en-US.json
.dumi/theme/locales/zh-CN.json
packages/web3/src/ethereum/index.md

docs: support search in all icon

---

.changeset/blue-kiwis-leave.md
packages/ton/README.md

add README.md for `@ant-design/web3-ton`

chore: add readme for @ant-design/web3-ton

---

.changeset/wild-ants-speak.md
packages/web3/src/connect-button/style/index.ts

 fix: remove useless margin in quick connect mode button

---

.changeset/gorgeous-shoes-wash.md
packages/common/src/types.ts
packages/wagmi/src/interface.ts
packages/wagmi/src/wagmi-provider/__tests__/basic.test.tsx
packages/wagmi/src/wagmi-provider/config-provider.tsx
packages/wagmi/src/wagmi-provider/index.tsx
packages/wagmi/src/wallets/__tests__/mobile-wallet.test.tsx
packages/wagmi/src/wallets/__tests__/wallet-connect.test.tsx
packages/wagmi/src/wallets/universal-wallet.tsx
packages/wagmi/src/wallets/wallet-connect.ts
packages/web3/src/connect-modal/__tests__/qrcode.test.tsx
packages/web3/src/connect-modal/components/ModalPanel.tsx
packages/web3/src/connect-modal/components/WalletList.tsx
packages/web3/src/connector/__tests__/basic.test.tsx
packages/web3/src/connector/connector.tsx
packages/web3/src/ethereum/demos/web3modal.tsx
packages/web3/src/types/index.md
packages/web3/src/types/index.zh-CN.md

close https://github.com/ant-design/ant-design-web3/issues/982

feat: support useWalletConnectOfficialModal for wagmi provider and add customQrCodePanel for wallet

---

.dumi/theme/builtins/HomePage/components/Banner/index.module.less

feat: 首页 slogan 展示优化

---

.dumi/theme/builtins/HomePage/components/Features/index.module.less
.dumi/theme/builtins/HomePage/components/Features/index.tsx

site: fix homepage features in dark mode

---

.dumi/theme/builtins/HomePage/components/ShowCase/NFTCard.tsx

docs: update nft image url in demo

---

examples/eth-web3js/package.json
examples/ethers-v5/package.json
examples/ethers/package.json
pnpm-lock.yaml

Reverts ant-design/ant-design-web3#1178

Revert "chore(deps): bump umi from 4.1.5 to 4.3.22"

---

.dumirc.ts
packages/web3/global.d.ts
packages/web3/src/solana/demos/more-components.tsx
packages/web3/src/solana/demos/sign-message.tsx

[ZAN.top](https://zan.top/home/node-service?chInfo=ch_antdweb3) 已支持 Solana 主网，将 rpc 接口统一。

site: switch Solana rpc provider to ZAN

---

README-zh_CN.md
README.md

docs: add sponsor links

---

.changeset/plenty-flowers-live.md
packages/web3/src/crypto-input/__tests__/index.test.tsx
packages/web3/src/crypto-input/index.tsx

before:
https://github.com/user-attachments/assets/c7699498-c94b-4545-80ae-0543183a5be8
https://github.com/user-attachments/assets/da4e3993-87cb-4703-a04d-f503b92a6ab6
After:
https://github.com/user-attachments/assets/5ae72802-08d1-4901-b2e7-725a2a518e06

feat: Optimize the input interaction of the CryptoInput component

---

packages/web3/src/ethereum/demos/siwe/index.tsx
packages/web3/src/ethereum/demos/siwe/mock-api.ts
packages/web3/src/ethereum/demos/siwe/sign-btn.tsx
packages/web3/src/ethereum/index.md
packages/web3/src/ethereum/index.zh-CN.md
vitest.config.mts

docs: add SIWE demo

---

.changeset/brown-fishes-speak.md
packages/icons/README.md

优化了一下 README 
for https://www.npmjs.com/package/@ant-design/web3-icons

docs: update @ant-design/web3-icons readme

---

package.json

应该也没啥坏处，有问题的话后期再revert好了。先加一下吧，vite这边的menorepo也有加上，应该没啥坏处。

chore: add keywords for package.json

---

packages/ton/src/ton-provider/__tests__/basic.test.tsx
packages/ton/src/ton-provider/__tests__/sdk.test.tsx
packages/wagmi/src/wagmi-provider/__tests__/basic.test.tsx
packages/wagmi/src/wagmi-provider/__tests__/config-with-ssr-wallet.test.tsx
packages/wagmi/src/wagmi-provider/__tests__/ens.test.tsx
packages/wagmi/src/wallets/coinbase-wallet.tsx
packages/web3/src/connect-modal/demos/empty.tsx
packages/web3/src/crypto-input/index.tsx
packages/web3/src/ethereum/demos/siwe/index.tsx
packages/web3/src/ethereum/demos/siwe/sign-btn.tsx

chore(code-style): lint fix

---

.dumi/theme/builtins/ThemeEditorPage/demos/address.tsx
.dumi/theme/builtins/ThemeEditorPage/demos/browser-link.tsx
.dumi/theme/builtins/ThemeEditorPage/demos/connect-button.tsx
.dumi/theme/builtins/ThemeEditorPage/demos/connect-modal.tsx
.dumi/theme/builtins/ThemeEditorPage/demos/crypto-price.tsx
.dumi/theme/builtins/ThemeEditorPage/demos/index.ts
.dumi/theme/builtins/ThemeEditorPage/demos/nft-card.tsx
docs/guide/ant-design-web3.md
docs/guide/ant-design-web3.zh-CN.md
docs/guide/theme.md
docs/guide/theme.zh-CN.md
packages/web3/src/connect-modal/demos/panel.tsx

精简主题编辑器中的 Demo，让主题编辑器看上去更简洁，更好用

docs: improve theme edtor

---

packages/web3/src/solana/index.md
packages/web3/src/solana/index.zh-CN.md

docs(solana): Update doc link

---

.dumi/theme/builtins/HomePage/components/Banner/index.module.less
.dumi/theme/builtins/HomePage/components/Banner/index.tsx
.dumi/theme/builtins/HomePage/components/Features/index.tsx
.dumi/theme/builtins/HomePage/components/ShowCase/Connect.tsx
.dumi/theme/builtins/HomePage/components/ShowCase/CryptoInput.tsx
.dumi/theme/builtins/HomePage/components/ShowCase/NFTCard.tsx
.dumi/theme/builtins/HomePage/components/ShowCase/PayPanel.tsx
.dumi/theme/builtins/HomePage/components/ShowCase/index.tsx
.dumi/theme/builtins/HomePage/components/Theme/index.tsx
.dumirc.ts

docs: improve seo

---

.changeset/happy-camels-speak.md
packages/assets/src/solana/__tests__/browser-link.test.ts
packages/assets/src/solana/chains.tsx

fix(assets): Solana testnet and devent browser URL is incorrect

---

.changeset/poor-beans-dream.md
packages/wagmi/src/wagmi-provider/__tests__/custom-config.test.tsx
packages/wagmi/src/wagmi-provider/index.tsx

Reverts ant-design/ant-design-web3#1278

Revert "fix: incorrect chains error log"

---

README-zh_CN.md
README.md

docs: Update readme

---

.dumi/pages/index-cn/index.tsx

close https://github.com/ant-design/ant-design-web3/issues/1296

fix: add index cn home page

---

docs/guide/demos/best-practice/components/pay-button.tsx

fix: Remove duplicates （Connector）

---

.dumirc.ts

close https://github.com/ant-design/ant-design-web3/issues/1286

fix: site style in dark mode

---

packages/eth-web3js/src/web3js-provider/web3js-provider.tsx
packages/ethers/src/ethers-provider/ethers-provider.tsx

fix ci for commit https://github.com/ant-design/ant-design-web3/commit/ff8c26c28216f332262755f4571c8b53f51dea2f (不小心直接 push 到 main 了)

fix: ts error after upgrade wagmi

---

docs/course/dev-connect.zh-CN.md

remove the extra code in chinese guid docoument.
document link: https://web3.ant.design/course/dev-connect-cn#%E9%85%8D%E7%BD%AE%E9%80%82%E9%85%8D%E5%99%A8
`-`

docs: remove unnecessary code

---

.changeset/hip-vans-laugh.md
.github/workflows/preview-build.yml
packages/solana/CHANGELOG.md
packages/solana/package.json

release @ant-design/web3-solana@1.2.6

chore: release @ant-design/web3-solana@1.2.6

---

docs/guide/demos/tokens.ts

feat: new theme win95

---

.changeset/chilly-rice-clap.md
packages/web3/src/crypto-input/__tests__/index.test.tsx
packages/web3/src/crypto-input/index.md
packages/web3/src/crypto-input/index.tsx
packages/web3/src/crypto-input/index.zh-CN.md

feat: add hide max button

---

.changeset/fifty-pianos-agree.md
packages/ton/src/wallets/myTonWallet.tsx
packages/ton/src/wallets/okxTonWallet.tsx
packages/ton/src/wallets/openmask.tsx
packages/ton/src/wallets/tonkeeper.tsx

chore: add wallet extensions info

---

packages/web3/src/connect-button/demos/balance.tsx

chore: update balance demo

---

README-zh_CN.md
README.md

[English Template / 英文模板](https://github.com/ant-design/ant-design/blob/master/.github/PULL_REQUEST_TEMPLATE.md?plain=1)
https://github.com/ant-design/ant-design-web3/discussions/1399
新版展示图表展示如下：

docs: update the new Readme contributors charts

---

README-zh_CN.md
README.md

简化 readme，只需要一个 Contributing 图片

feat: update readme, remove some contributors images

---

README.md

docs: fix readme miss coverage info issue

---

packages/web3/src/connect-modal/__tests__/__snapshots__/basic.test.tsx.snap
packages/web3/src/connect-modal/__tests__/__snapshots__/simple.test.tsx.snap
packages/web3/src/connect-modal/__tests__/get-wallet.test.tsx
packages/web3/src/connect-modal/__tests__/mock/index.ts
packages/web3/src/connect-modal/__tests__/panel.test.tsx
packages/web3/src/connect-modal/__tests__/qrcode.test.tsx
packages/web3/src/connect-modal/demos/basic.tsx
packages/web3/src/connect-modal/demos/customGuide.tsx
packages/web3/src/connect-modal/demos/panel.tsx
packages/web3/src/connect-modal/demos/simple.tsx
packages/web3/src/connect-modal/demos/ungroupedBasic.tsx
packages/web3/src/web3-config-provider/__tests__/mock/index.ts

chore: update test image url

---

.cursor/rules/basic.mdc

chore: add cursor rules

---

packages/web3/src/nft-card/__tests__/basic.test.tsx
packages/web3/src/nft-card/demos/basic.tsx
packages/web3/src/nft-card/demos/dark-mode.tsx

chore: fix demos image url

---

README-zh_CN.md
README.md

chore: remove start hisitory from readme
