packages/web3/src/connect-button/__tests__/index.test.tsx, packages/web3/src/connect-button/connect-button.tsx, packages/web3/src/connect-button/demos/tooltip.tsx, packages/web3/src/connect-button/index.md, packages/web3/src/connect-button/index.zh-CN.md, packages/web3/src/connect-button/interface.ts, packages/web3/src/connect-button/tooltip.tsx, packages/web3/src/utils/test-utils.ts
=> feat: Support tooltip

packages/common/src/types.ts, packages/wagmi/src/wagmi-provider/config-provider.tsx, packages/wagmi/src/wagmi-provider/index.tsx, packages/wagmi/src/wagmi-provider/methods/addNameToAccounts.ts, packages/wagmi/src/wagmi-provider/methods/getNFTMetadata.ts, packages/wagmi/src/wagmi-provider/methods/index.test.ts, packages/wagmi/src/wagmi-provider/methods/index.ts, packages/web3/src/connector/__tests__/name.test.tsx, packages/web3/src/connector/conector.tsx, packages/web3/src/connector/demos/name.tsx, packages/web3/src/connector/index.md, packages/web3/src/connector/index.zh-CN.md
close #67 
通过在 `WagmiWeb3ConfigProvider` 配置 `ens` 来支持默认请求 ENS 并显示。
=> feat: wagmi provider support ENS

.dumi/app.tsx, .dumi/tsconfig.json, packages/web3/src/address/index.tsx, packages/web3/src/connect-button/__tests__/index.test.tsx, packages/web3/src/connect-button/__tests__/tooltip.test.tsx, packages/web3/src/connect-button/connect-button.tsx, packages/web3/src/connect-button/demos/simple.tsx, packages/web3/src/connect-button/demos/type.tsx, packages/web3/src/connect-button/index.md, packages/web3/src/connect-button/index.zh-CN.md, packages/web3/src/utils/format.ts, packages/web3/src/utils/index.ts
- 修改文档的 primaryColor，设计稿中的主色调的修改应该是通过 antd Design token  实现的，不应该在组件中写死，如果用户没有配置的话就应该用 antd 默认的主题色， @kiner-tang ConnectModal 里面的逻辑应该也要修改。
- 修改了 tooltip 的显示逻辑：默认补全地址的 0x 前缀以及不缩略显示地址
=> feat: custom primary color and fix tooltip bug

packages/web3/src/nft-image/__tests__/index.test.tsx
增加nft image单测：
1. 使用有效的地址和 tokenId 进行正常渲染的测试用例。
2. 使用有效的地址和 bigint 类型的 tokenId 进行正常渲染的测试用例。
=> feat: 增加nft image test

.changeset/fuzzy-balloons-check.md, packages/web3/src/connect-modal/__tests__/__snapshots__/basic.test.tsx.snap, packages/web3/src/connect-modal/__tests__/qrcode.test.tsx, packages/web3/src/connect-modal/components/QrCode.tsx, packages/web3/src/connect-modal/style/index.tsx
添加二维码的连接，这样手机访问的时候可以直接点击链接连接，而不需要扫码，因为没办法自己扫自己。
=> feat: add link for wallet qrcode for support connect in mobile

.dumi/global.less
问题描述：官网英文版，footer 中的标题显示不全
我猜想原因可能是
footer的height是14px，但是nav的a标签内部font-size是16px，所以这个lineheight不对，导致显示异常，设置成1.2可以解决这个问题
修复后的效果
=> style: fix dumi-default-footer line-height

.changeset/calm-planes-provide.md, .changeset/fuzzy-jars-breathe.md, .changeset/smart-goats-approve.md, packages/assets/CHANGELOG.md, packages/assets/package.json, packages/common/CHANGELOG.md, packages/common/package.json, packages/icons/CHANGELOG.md, packages/icons/package.json, packages/wagmi/CHANGELOG.md, packages/wagmi/package.json, packages/web3/CHANGELOG.md, packages/web3/package.json
@ant-design/web3 这个包之前误发过 1.0.0，unpublished 了也不能重发。所以发的是 1.0.1
=> chore: release 1.0.0

.github/workflows/preview-build.yml
现在 dumi 的构建方式改了，直接从源代码构建，不需要这个了。
=> chore: remove build in preview

docs/course/dev-connect.zh-CN.md
感觉这一块的安装命令可以参考 `快速开始`中的
修改完之后更好看，更好用，因为现在的确选择yarn、pnpm的用户可能更多
=> docs: optimize document

.changeset/eight-lizards-peel.md, .changeset/gold-shrimps-buy.md, .changeset/hip-seals-swim.md, .changeset/large-drinks-provide.md, .changeset/long-cheetahs-film.md, .changeset/metal-pots-jog.md, .changeset/perfect-chefs-divide.md, .changeset/pink-yaks-check.md, .changeset/real-chefs-protect.md, .changeset/slimy-lamps-act.md, .changeset/thirty-owls-destroy.md, .dumi/theme/builtins/IconSearch/fields.ts, packages/assets/CHANGELOG.md, packages/assets/package.json, packages/common/CHANGELOG.md, packages/common/package.json, packages/icons/CHANGELOG.md, packages/icons/package.json, packages/wagmi/CHANGELOG.md, packages/wagmi/package.json, packages/web3/CHANGELOG.md, packages/web3/package.json
1.1.0 and 1.1.1 因为之前有 PR 的 changlog 写成 major 了，发布的时候有错误，所以重新发布 1.1.2 成功，之前两个版本废弃。
=> chore: release 1.1.2

.changeset/tough-shirts-tan.md, .github/workflows/changeset-check.yml
好像还缺少一些权限
接口文档: https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28
https://github.com/thinkasany/PR-template/pull/1
=> ci(Changeset): auto add label

.github/workflows/preview-start.yml
对比antd，缺少了 ```preview-start.yml```, preview-startd 的评论是这个ci触发的。
=> ci: add preview-start comment

.changeset/nice-items-search.md, packages/web3/src/address/__tests__/index.test.tsx, packages/web3/src/address/index.tsx, packages/web3/src/hooks/demos/useConnection.tsx
Updates:
1. Update the copy address feature to incorporate a more internationalized interaction. For example, some leading web3 companies include openzeppelin.com 、consensys.io、etherscan.io and others.
2. Provide feedback in the connectwallet example after providing the link, as the Metamask pop-up won't appear when connecting again.
=> Copy address to try a more internationalized interaction

docs/guide/contributing.md, docs/guide/contributing.zh-CN.md
Some contributors have not used changeset before, and it is easy to misoperate when operating. Add changeset's new changelog user guide link.
=> docs: update docs about changeset

packages/web3/src/connect-button/index.md, packages/web3/src/wagmi/index.md
重命名示例标题，避免跟后面的 Balance 的 API 表格命名冲突跳转异常
=> docs: opt connect-button docs

packages/web3/src/connect-button/connect-button.tsx
这边 account不存在的话都直接返回下面actionsMenu了，所以可以直接用defaultMenuItems没必要再套一个account的 三元
=> chore: opt connect-button's combinedItems

.changeset/shy-rice-smash.md, packages/web3/src/connect-button/connect-button.tsx
locale为中文时，`Copy Address` 显示英文。
=> fix: fix intl for connect-button

package.json
Node.js 18开始，fetch才成为全局api，现在这边的16在本地跑单测的时候会挂，可以改成18。
=> feat: upgrade node engines to 18

.changeset/khaki-tips-sparkle.md, packages/wagmi/src/wagmi-provider/__tests__/more-wallets-connect.test.tsx, packages/wagmi/src/wagmi-provider/config-provider.tsx, packages/wagmi/src/wallets/meta-mask.ts, packages/wagmi/src/wallets/universal-wallet.tsx
- 当开发者配置了 eip6963 时，不需要配置 Connector 也正常显示 wallet，会使用基于 eip6963 自动检测到的 connector
- MetaMask 也改为了基于 UniversalWallet 实现，修复了这个相同的问题
=> fix: Show wallet which not config connector when eip6963 is true

.changeset/rare-items-roll.md, .fatherrc.base.ts, package.json, packages/assets/package.json, packages/common/package.json, packages/common/src/web3-config-provider/index.tsx, packages/icons/package.json, packages/wagmi/package.json, packages/web3/package.json, pnpm-lock.yaml
- ESM 现在应该是更主流更新更流行的打包方式了，`main` 字段默认改为 esm 的，对应 `type` 也修改为 `module`，这样在大部分框架中得以更好的默认支持。在 NextJS 和 Remix 中都是如此。可以 close #519 
- 默认添加 `.js` 的后缀，不然在 NexJS 和 Remix 这样可能在 NodeJS 环境运行 esm 的框架中会报找不到模块。
=> fix: use esm import as the default import way for fix use in Remix

.changeset/eleven-eagles-deliver.md, packages/web3/src/connect-button/style/index.ts
#511 
demo 缺少`margin-inline-start: 8px;`
=> fix: Profile Modal lack space

.changeset/tender-buckets-peel.md, packages/web3/src/connect-modal/__tests__/MainPanelHeader.test.tsx
最后两个关于test ci覆盖的pr补充上就100% coverage了
=> test: Increase ConnectModal's components test coverage

.changeset/little-clocks-bathe.md, packages/web3/src/browser-link/index.tsx
这段代码是deadcode
如果`React.isValidElement`为false的时候直接返回`mergedIcon`了, 不需要在合并style的时候再做一次三元运算.
清除这段代码还能提高一下覆盖率
=> refactor: displayIcon of the BrowserLink

packages/web3/src/connect-button/__tests__/tooltip.test.tsx, packages/web3/src/connect-button/index.md, packages/web3/src/connect-button/index.zh-CN.md
发现codecov 覆盖其实没有覆盖100%，我最近慢慢抽空把这个覆盖了。
=> test: Increase ConnectButton's tooltip test coverage

packages/web3/src/connect-button/__tests__/connect.test.tsx, packages/web3/src/connect-button/__tests__/index.test.tsx, packages/web3/src/connector/__tests__/basic.test.tsx
=> test: Increase ConnectButton & Connector test coverage

.changeset/eight-frogs-tan.md, packages/web3/src/connector/__tests__/basic.test.tsx, packages/web3/src/connector/connector.tsx
#529 之前这个pr中提到的错误是因为```React.cloneElement``` 导致的，并且下面这段代码也是执行不到的，没意义的，因为如果不是合法的时候已经页面报错了，所以可以再进一步优化一下，顺便还能提高一下覆盖率
=> refactor: modify connector code

.changeset/shy-plants-deliver.md, packages/common/src/utils/index.ts
close #553
确实warning没打包出来，需要export一下打包才出来。
=> fix: connect-button warning

docs/guide/contribute-icons.md, docs/guide/contribute-icons.zh-CN.md
根据 @LCJove 提供的信息，完善了「如何贡献图标」的文档，以便项目方主动贡献。另外应当增加一个 issue template，当项目方没有贡献能力的情况下可以给我们提需求。
Preview:
* 英文：https://preview-594-ant-design-web3.surge.sh/guide/contribute-icons
* 中文：https://preview-594-ant-design-web3.surge.sh/zh-CN/guide/contribute-icons
=> docs: how to contribute icons

.changeset/happy-penguins-taste.md, packages/web3/src/connect-modal/style/index.tsx
重新修复了一下connect的圆角问题
原因是因为main-panel设置了背景色之后，覆盖在了modal 上面，导致圆角被覆盖了
=> re-fix connect modal radius

packages/assets/src/chains/ethereum.tsx, packages/common/src/types.ts, packages/web3/src/wagmi/demos/chains.tsx
目前针对 `wagmi/chains` 未提供的链配置如何提供还没有统一的方案，而且和我们自己的链配置 Chain 信息有很大重叠。
Fix #600
=> Support okx x1 testnet

.changeset/six-toys-burn.md, .dumirc.ts, .fatherrc.base.ts, docs/guide/contribute-icons.md, docs/guide/contribute-icons.zh-CN.md, package.json, packages/icons/package.json, packages/web3/package.json, pnpm-lock.yaml
close https://github.com/ant-design/ant-design-web3/issues/581
=> fix: use react-inline-svg-unique-id plugin for fix svg id issue in runtime

packages/web3/src/address/index.zh-CN.md, packages/web3/src/browser-link/index.zh-CN.md, packages/web3/src/connect-button/index.zh-CN.md, packages/web3/src/connect-modal/index.zh-CN.md, packages/web3/src/connector/index.zh-CN.md, packages/web3/src/crypto-price/index.zh-CN.md, packages/web3/src/hooks/index.zh-CN.md, packages/web3/src/icons/index.zh-CN.md, packages/web3/src/nft-card/index.zh-CN.md, packages/web3/src/nft-image/index.zh-CN.md, packages/web3/src/solana/index.zh-CN.md, packages/web3/src/types/index.zh-CN.md, packages/web3/src/wagmi/index.zh-CN.md, packages/web3/src/web3-config-provider/index.zh-CN.md
使用副标题优化组件文档，更好的区分中文翻译和原文，也更美观。
=> chore: use subtitle for zh-CN

.github/workflows/release-tweet.yml
最终这边的tag会替换`${{ github.event.ref }}`, 
🤖 Ant Design Web3 just released ${{ github.event.ref }} ✨🎊✨ Check out the full release note: https://github.com/ant-design/ant-design-web3/releases/tag/${{ github.event.ref }}
即：
🤖 Ant Design Web3 just released @ant-design/web3@1.8.0 ✨🎊✨ Check out the full release note: 
https://github.com/ant-design/ant-design-web3/releases/tag/@ant-design/web3@1.8.0
=> ci: tweet when release is published

.github/workflows/release-dingtalk.yml
发送消息，并创建pre-release
需要佬们配置一个bot，并在仓库设置 `WEB3_DINGDING_BOT_TOKEN`
目前这个勉强够用，如果后面有一些定制化任务，我可以做一个action专门用于该仓库定制的消息通知。
=> ci: DingTalk Release Notification

.changeset/smooth-trees-stare.md, packages/common/src/locale/en_US.ts, packages/common/src/locale/zh_CN.ts, packages/common/src/types.ts, packages/web3/src/connect-modal/components/QrCode.tsx, packages/web3/src/connector/__tests__/quick-connect.test.tsx
fix: qr code scan tip text for universal protocol
通用协议的二维码不是某一个特定钱包的二维码，文案要对应改一下。
=> fix: qr code scan tip text for universal protocol

.dumi/theme/builtins/HomePage/components/ShowCase/Connect.tsx, .dumi/theme/builtins/HomePage/components/ShowCase/index.module.less
=> fix: Connect Wallet style in DemoShow

.changeset/funny-flies-hug.md, .dumi/theme/builtins/HomePage/components/Theme/index.tsx, docs/guide/demos/custom-token.tsx, docs/guide/demos/theme.tsx, packages/web3/src/connect-modal/demos/panel.tsx
=> chore(card): use `styles.body` instead of `bodyStyle`

.github/workflows/release-dingtalk.yml
之前不会触发trigger可能是因为tag是老的，所以重新发布也没用，我多次测试了一下都能正常发布（也遇到了老的tag不触发，新的tag都是正常的）。
怀疑第一次skip也是因为同时触发了太多次的tag 所以导致了skip
但是由于项目的特殊性，的确tag不是很合适，会同时出现好几个tag，release-helper 不能很好的支持release，里面的代码过度依赖tag了，也没有对应监听release的属性，因此我fork下来做了改动。在后期维护上，我会使用@dev分支测试，@main做为稳定版不影响项目的正常使用 。
现在都是取release的参数，更适合本项目的自动化。
具体代码逻辑几十行，就是替换了一下yml的配置和调用了钉钉的webhook，维护起来成本也不高，后续针对markdown格式也更好私人订制。
https://github.com/thinkasany/release-helper/blob/main/src/main.ts
=> ci: Replacing release-helper's uses

.changeset/unlucky-knives-visit.md, docs/course/dev-connect.md, docs/course/dev-connect.zh-CN.md, docs/guide/quick-start.md, docs/guide/quick-start.zh-CN.md, packages/wagmi/package.json, packages/wagmi/src/wagmi-provider/config-provider.tsx, packages/wagmi/src/wallets/__tests__/im-token.test.tsx, packages/wagmi/src/wallets/__tests__/okx-wallet.test.tsx, packages/wagmi/src/wallets/__tests__/token-pocket.test.tsx, packages/web3/src/wagmi/demos/recommend.tsx, packages/web3/src/wagmi/index.md, packages/web3/src/wagmi/index.zh-CN.md, pnpm-lock.yaml
@tanstack/react-query 和 wagmi 一样应该是 peerDependencies，wagmi 中 peerDependencies 依赖了 @tanstack/react-query，wagmi 是 peerDependencies，@tanstack/react-query 应该也是 peerDependencies。不然构建工具打包的时候可能会重复构建多次 @tanstack/react-query，导致 context 不对。
issue 中出现的问题就是因为虽然在 `@ant-design/web3-wagmi` 中我们初始化并提供了 queryClient，但是在 wagmi 中使用的 react-query context 和 `@ant-design/web3-wagmi` 中的并不是同一个，所以会报没有初始化 queryClient。
close #501
=> fix: move @tanstack/react-query to peerDependencies for fix react-query context error

.changeset/pretty-ducks-hide.md, .github/workflows/pr-contributor-welcome.yml, .github/workflows/preview-deploy.yml, README-zh_CN.md, README.md, packages/web3/src/connect-button/connect-button-inner.tsx, pnpm-lock.yaml
https://github.com/ant-design/ant-design-web3/issues/705
=> docs: img add default alt (#705)

.dumi/theme/builtins/ThemeEditorPage/index.tsx
是 import 'antd/es/style/reset.css'; 引入了 h1 {margin-bottom: 0.5em; } 从而导致污染全局样式的话。
对比两个pr的preivew，在677的时候都是好的，最后排查到`import 'antd/es/style/reset.css` 的影响，试了一下打包后的dist用express.static去加载看了是好的，一会观察一下preivew。
https://preview-664-ant-design-web3.surge.sh/components/icons
https://preview-677-ant-design-web3.surge.sh/course/introduction
close #700
<!--
1. Put the related issue or discussion links here.
2. close #xxxx or fix #xxxx for instance.
=> fix: Official Website Document UI anomaly

.github/workflows/pr-labeled.yml
针对pr的自动评论，有时候用户不熟悉我们的changelog规范，通过打label来自动回复可以节省我们重复整理并发送教程的步骤, 后续可以逐步补充label以及对应的教程。
=> ci: add PR Labeled

.github/workflows/pr-labeled.yml
1. `github.actor` 是触发者，之前那个ci可以是因为是监听pr事件的，现在这边监听的是label，会艾特到打label的人有点错误。
2. trigger 也得修改，否则对fork的分支无法生效
=> chore(ci): update mentioned

.dumirc.ts, .fatherrc.base.ts
1.  fill 写到了 style 里面，导致引用的时候颜色丢失
2. svgo 会移除 viewBox 的问题
🫡 @LCJove 
#738
=> chore(BabelPlugins): overrides configuration for svgo

packages/icons/src/__tests__/index.test.tsx
目前icon的 id 都是运行时每次自动生成的，这段test case用不上了，只会拖长执行时间
=> test(icon): remove unused case

.changeset/sweet-roses-drum.md, packages/assets/src/chains/ethereum.tsx, packages/common/src/types.ts
feat(ether): support ether testnet 'Sepolia' 
The ether testnet Sepolia is not currently supported in the code. The Goerli testnet is about to go offline, so add Sepolia support.
=> feat(ether): support ether testnet 'Sepolia' 

package.json, packages/icons/scripts/generate.ts, pnpm-lock.yaml
参考@Wxh16144 大佬 pr(https://github.com/ant-design/ant-design-icons/pull/635), 实现了icon-preview(通过jsdoc, 鼠标放在组件上可以看到icon的样式)，因为打包方式、产物以及命名上有一些不同，所以在代码上略有改造。
这个同步脚本应该后续也用得上，略加改造同步 svg 可以提高后续添加 svg 的效率直接拖入图片就可以转成组件代码，降低cv和命名心智，
目前部分目录会有点问题，佬们看看是需要重命名呢，还是跳过这些文件，还是完善正则去兼容。
=> feat: support icons:generate

.changeset/six-laws-jump.md, packages/solana/package.json, packages/solana/src/index.ts, packages/solana/src/solana-provider/__tests__/connect-error.test.tsx, packages/solana/src/solana-provider/__tests__/connect.test.tsx, packages/solana/src/solana-provider/__tests__/wallet-connect.test.tsx, packages/solana/src/solana-provider/config-provider.tsx, packages/solana/src/solana-provider/index.tsx, packages/solana/src/solana-provider/useWalletConnectProvider.ts, packages/solana/src/types.ts, packages/solana/src/utils.ts, packages/solana/src/wallet-connect-adapter.ts, packages/solana/src/wallets/built-in.ts, packages/solana/src/wallets/factory.ts, packages/solana/src/wallets/types.ts, packages/web3/package.json, packages/web3/src/connect-modal/components/QrCode.tsx, packages/web3/src/solana/demos/sign-message.tsx, packages/web3/src/solana/demos/wallet-connect.tsx, packages/web3/src/solana/index.md, packages/web3/src/solana/index.zh-CN.md, pnpm-lock.yaml
添加 WalletConnect 连接方式，处理连接错误。
测试用例稍后补充。
=> feat(solana): support wallet-connect and handle connect error

.changeset/red-doors-drop.md, packages/web3/src/connect-modal/__tests__/__snapshots__/basic.test.tsx.snap, packages/web3/src/connect-modal/__tests__/__snapshots__/simple.test.tsx.snap, packages/web3/src/connect-modal/components/QrCode.tsx, packages/web3/src/connect-modal/components/WalletList.tsx, packages/web3/src/connect-modal/demos/basic.tsx, packages/web3/src/connect-modal/style/index.tsx
对connect modal 的一些优化工作，
1. 整体的高度不会变化，因此需要对一些内容添加overflow
2. 插件的按钮的位置进行优化，避免右侧出现大量空白
3. 钱包名字过长时，省略展示
close #653
=> feat: optimize connect modal UI

.dumi/theme/layouts/GlobalLayout.tsx, package.json, pnpm-lock.yaml
项目中定义的 `GlobalLayout` 与主题中的相冲突，导致移动端适配逻辑未生效
Close #612
Close #745
=> chore: doc site supports mobile

.github/workflows/ci.yml, .github/workflows/preview-build.yml
目前ci pnpm 和项目配置不一样会出错，需要版本号一致。
=> ci: lock pnpm@8.9.0 version

.changeset/strong-wasps-serve.md, packages/solana/src/solana-provider/__tests__/standard-wallet.test.tsx, packages/solana/src/solana-provider/config-provider.tsx, packages/solana/src/solana-provider/index.tsx, packages/web3/src/solana/demos/recommend.tsx, packages/web3/src/solana/index.md, packages/web3/src/solana/index.zh-CN.md
可以自动将用户已经在浏览器安装插件的钱包添加到 Wallet Lists 中。
- 在 SolanaWeb3ConfigProvider 添加了一个 `autoAddRegisteredWallets` 属性，默认为 `false`
=> feat(solana): Support auto add registered wallets

.changeset/tough-items-leave.md, packages/web3/src/connect-button/__tests__/quick-connect.test.tsx, packages/web3/src/connect-button/connect-button-inner.tsx, packages/web3/src/connect-button/style/index.ts
- Fix icon align
- Add `ant-web3-connect-button-quick-connect`
文本和图标水平对齐稍微有点歪，实际测试下来发现不需要 Space
---
| Chain | Preview | Note |
|:-|-|-|
| Ethereum | ![image](https://github.com/ant-design/ant-design-web3/assets/18319675/8bc44d82-c232-4517-91b5-4acb18ba0234) | 这里的图标中，<br />图片留白比较多，<br />实际内容部分（红色）比较小所以看不太出来。|
| Solana | ![image](https://github.com/ant-design/ant-design-web3/assets/18319675/6d0c1919-31a1-45aa-9d6e-56b7423299e0) | 这个图标红色部分是铺满的，看起来就比较明显。 |
--- 
|Ethereum| ![image](https://github.com/ant-design/ant-design-web3/assets/18319675/70003e9f-d3f0-4a21-b826-369f01631795) |
|-|-|
|**Solana**| ![image](https://github.com/ant-design/ant-design-web3/assets/18319675/6c23b739-f59a-4262-bee8-4616f1798708) |
=> style: fix quick connect button icon align

.changeset/smart-gifts-hunt.md, packages/wagmi/src/wagmi-provider/config-provider.tsx
NFTCard 渲染的时候可能会出现 Error: Maximum update depth exceeded  这样的错误，原因是 getNFTMetadata 方法每次生成的引用都不同，导致 react 重复渲染
=> fix: useCallback for getNFTMetadata for avoid ‘Error: Maximum update depth exceeded’

docs/course/dev-call-contract.zh-CN.md
=> docs:修改文档中不通顺的句子

.changeset/long-eagles-brush.md, packages/web3/src/nft-card/NFTCard.tsx, packages/web3/src/nft-card/__tests__/action.test.tsx, packages/web3/src/nft-card/__tests__/basic.test.tsx, packages/web3/src/nft-card/__tests__/like.test.tsx, packages/web3/src/nft-card/demos/error.tsx, packages/web3/src/nft-card/index.md, packages/web3/src/nft-card/index.zh-CN.md
现在如果请求 NFT 信息错误会出现空白，显示不友好，加上错误提示。
before：
after：
=> feat: NFTCard add new prop errorRender

packages/web3/src/connect-modal/demos/basic.tsx, packages/web3/src/connect-modal/demos/ungroupedBasic.tsx
dumi2.3.2 useIntl 变成运行导出了，tmp文件中导出的useIntl, 这一块build的ci会过不去。不过感觉
```import { useIntl } from 'dumi';```用在demo是不是也不太合适，用户应该用自己的方法去判断国际化，或者说复制过去能马上能运行的，不然还得安装个dumi才能用这个。
=> refactor: remove useIntl for connect-modal demos

packages/web3/src/bitcoin/demos/basic.tsx, packages/web3/src/connect-button/index.md, packages/web3/src/connect-button/index.zh-CN.md, packages/web3/src/connect-modal/index.md, packages/web3/src/connect-modal/index.zh-CN.md, packages/web3/src/connector/index.md, packages/web3/src/connector/index.zh-CN.md, packages/web3/src/solana/demos/recommend.tsx, packages/web3/src/solana/index.md, packages/web3/src/solana/index.zh-CN.md
- 修复组件文档排序的问题，去掉之前指定的排序，默认会按照首字母排序
- Solana 和 Bitcoin 第一个 demo 中配置 group 为 false，因为他们默认的钱包都是在一个分组
=> docs: update doc detail

.changeset/rotten-badgers-wait.md, packages/web3/src/connector/__tests__/basic.test.tsx, packages/web3/src/connector/connector.tsx, packages/web3/src/connector/interface.ts
有些钱包在连接失败时，抛出的异常中没有 message，这种情况目前只会提示一个：
（目前只在使用 Solana 的一些钱包时出现。）
这个 pr 在 Connector 中添加了 onConnectError 属性，便于让开发者自己处理连接失败情况。
```tsx
<Connector
onConnectError={(error) => {
message.error(error?.message || 'Connect Error');
}}
>
<ConnectButton />
</Connector>
```
=> feat: Connector support onConnectError

.changeset/funny-garlics-fly.md, packages/bitcoin/src/adapter/useBitcoinWallet.ts
重构引入原因如下：
引入React不使用，容易被格式化插件去掉，但是一但去掉会出现错误 
```如果没有引用 "packages/common/node_modules/@types/react/ts5.0"，则无法命名 "BitcoinAdapterContext" 的推断类型。这很可能不可移植。需要类型注释。ts(2742)```
=> refactor: import for bitcoin adapter

docs/course/advanced-more.zh-CN.md
Solidity 官网教程网址变更，原网址 /solidity-start 已失效
=> fix: Update Solidity tutorial link

packages/web3/src/nft-card/index.md
=> docs: add error demo to en docs

.changeset/great-otters-doubt.md, packages/assets/package.json, packages/bitcoin/package.json, packages/common/package.json, packages/ethers-v5/package.json, packages/ethers/package.json, packages/solana/package.json, packages/wagmi/package.json, packages/web3/package.json
除了 web3-icons 以外，其它包也都需要支持 treeshaking
https://github.com/ant-design/ant-design-web3/pull/858
=> fix: set sideEffects false for enable treeshaking

.changeset/brown-eyes-deny.md, packages/common/src/types.ts
新增 Token 基本类型，基于基本类型拓展出单链及多链 Token 类型，用于 TokenSelect/CryptoInput/PayPanel 组件
add TokenBase type, extends ChainToken and MultiChainToken type, suit for TokenSelect/CryptoInput/PayPanel Component
[TokenSelect/CryptoInput](https://github.com/ant-design/ant-design-web3/pull/893/files#diff-89d3255baa11f9ff859997702be5fbaf6ba63b1abb52585c41cbecd61e5cf44b)
[PayPanel](https://github.com/ant-design/ant-design-web3/pull/876/files#diff-dbb1494ced1ff3fbeb2a436017c370e5223f6324ca5eba0ad0ca1df29c6e897b)
=> feat: add common Token type

.changeset/silly-schools-return.md, packages/assets/src/wallets/mobile-wallet.tsx, packages/common/src/types.ts, packages/wagmi/src/wagmi-provider/config-provider.tsx, packages/wagmi/src/wallets/wallet-connect.ts, packages/web3/src/ethereum/demos/more-wallets.tsx
在 MobileWallet 实现中新增的 proxyConnectorName 不是必须的，可以去掉。MobileWallet 基于 WalletConnect 实现的，这个 PR 给 WalletConnect 加了 getWagmiConnector，这样就不需要用名字来找 Connector 了。
https://github.com/ant-design/ant-design-web3/pull/900
=> refactor: remove useless proxyConnectorName

.dumi/global.less
优化滚动条样式，windows 下有点丑 
目前
优化后
-
=> site: Optimize scroll bar style

.changeset/cuddly-countries-deliver.md, packages/ethers/src/hooks/use-ethers-signer.ts
修复 ethers 包内部的一个问题，当钱包连接了一个未被当前项目定义的 chain 时，`client.chain` 为 null
=> fix(ethers): useEthersSigner hook issue when chain not contain

.github/dependabot.yml, package.json, pnpm-lock.yaml
Related: https://github.com/ant-design/ant-design-web3/pull/946#issuecomment-2162044914
应该是之前某次发布时赶上了 dumi 的问题版本，当前最新的 dumi 没有这个问题了。
=> chore(workspace): use dumi sem-version

.dumi/theme/builtins/HomePage/components/Theme/index.module.less
=> fix: circle bg image in home page

.changeset/serious-ducks-jog.md, packages/common/src/types.ts, packages/wagmi/src/wagmi-provider/__tests__/config-with-eip6963-and-wallets.test.tsx, packages/wagmi/src/wagmi-provider/__tests__/config-with-eip6963-wallet.test.tsx, packages/wagmi/src/wagmi-provider/__tests__/connect-with-universal-wallet.test.tsx, packages/wagmi/src/wagmi-provider/__tests__/connect.test.tsx, packages/wagmi/src/wagmi-provider/__tests__/ens.test.tsx, packages/wagmi/src/wagmi-provider/__tests__/nft.test.tsx, packages/wagmi/src/wagmi-provider/__tests__/unconnected.test.tsx, packages/wagmi/src/wagmi-provider/config-provider.tsx, packages/web3/src/connector/__tests__/basic.test.tsx, packages/web3/src/connector/connector.tsx, packages/web3/src/connector/index.md, packages/web3/src/connector/index.zh-CN.md, packages/web3/src/connector/interface.ts, packages/web3/src/ethereum/demos/eip6963.tsx, packages/web3/src/types/index.md, packages/web3/src/types/index.zh-CN.md
`onConnected` 方法参数中没有连接的账号信息，在一些需求中会有需要，比如连接成功后请求地址相关信息。
该  PR 新增相关参数。
=> feat: onConnected callback support provider account

.changeset/blue-rats-sort.md, packages/web3/src/connect-modal/style/index.tsx
=> fix: wallet list scroll cover style in dark mode

.github/dependabot.yml
=> chore(dependabot): update update-type for ethers 

packages/web3/src/types/index.zh-CN.md
现在zh文档中， 中英文table title并存，统一为中文
before：
after：
=> docs(types): translate table titles in zh doc

.changeset/green-olives-deliver.md, packages/web3/src/crypto-input/index.md, packages/web3/src/crypto-input/index.zh-CN.md
由于不在使用 ConfigProvider 实现样式覆盖，删除 CryptoInput 组件中无用的主体变量模块
=> docs: remove unuseful ThemeToken about CryptoInput component

.changeset/lovely-horses-obey.md, packages/web3/package.json, packages/web3/src/crypto-input/index.tsx, pnpm-lock.yaml
=> fix: add lodash-es for @ant-design/web3

.changeset/strong-islands-happen.md, .dumi/theme/builtins/HomePage/components/ShowCase/CryptoInput.tsx, .dumi/theme/builtins/HomePage/components/ShowCase/PayPanel.tsx, packages/web3/src/connect-modal/style/index.tsx
1. 移动端宽度不到400px, 去掉card中配置的width
2. connect-modal footer mask 被left 挤出去了，既然用了绝对定位可以用`transform: 'translateX(-50%)'` 来水平居中。
#989
=> fix(mobile): width display overflow

.dumi/theme/builtins/HomePage/components/ShowCase/CryptoInput.tsx, docs/meetup2024/mint.tsx, packages/web3/src/bitcoin/demos/get-inscriptions.tsx, packages/web3/src/crypto-input/demos/basic.tsx, packages/web3/src/crypto-input/demos/customFooter.tsx, packages/web3/src/crypto-input/demos/customHeader.tsx, packages/web3/src/crypto-input/demos/noFooter.tsx, packages/web3/src/crypto-input/demos/sizeChange.tsx, packages/web3/src/crypto-input/demos/swapMode.tsx, packages/web3/src/pay-panel/demos/modal.tsx, packages/web3/src/token-select/demos/basic.tsx, packages/web3/src/token-select/demos/withSearch.tsx
函数组件都使用了 `React: FC`, 但很多未在顶部导出，用户如果复制demo的时候可能会提示错误。
我直接统一都加上了
=> type: import React type

.changeset/few-tools-perform.md, packages/web3/src/crypto-input/__tests__/index.test.tsx, packages/web3/src/crypto-input/index.tsx
1. remove unused antdTheme.useToken
2. improve classname，不带prefixCls的易于用户的自定义classname产生样式冲突
=> fix: improve crypto-input

.changeset/chilled-birds-help.md, package.json, packages/web3/package.json, packages/web3/src/address/__tests__/__snapshots__/index.test.tsx.snap, packages/web3/src/connect-button/__tests__/__snapshots__/profile-modal.test.tsx.snap, packages/web3/src/connect-button/__tests__/__snapshots__/tooltip.test.tsx.snap, packages/web3/src/connect-modal/__tests__/__snapshots__/basic.test.tsx.snap, packages/web3/src/connect-modal/__tests__/__snapshots__/simple.test.tsx.snap, packages/web3/src/nft-image/__tests__/__snapshots__/index.test.tsx.snap, packages/web3/src/web3-config-provider/__tests__/__snapshots__/index.test.tsx.snap, pnpm-lock.yaml
问题可能出在计算移至cssinjs这个更新，这个pr主要做了两处调整，1: cssinjs to 1.21.0 和 antd to 5.18.3，2. react 和 react-dom的锁死，不然可能ci会有很多报错，我在后面升级下一个antd版本的时候，react的版本和那边一起对齐好了。 我是想着antd5.19这个月初才刚发，我们可以等到月中或者月底再做升级。
目前fix了。close #1023
=> fix: ConnectModal style bug in dark theme

.changeset/fluffy-dingos-guess.md, .changeset/wicked-buttons-cover.md, docs/global.d.ts, docs/guide/ant-design-web3.md, docs/guide/ant-design-web3.zh-CN.md, docs/guide/demos/guide.module.less, docs/guide/demos/guide.tsx, docs/guide/demos/tokens.ts, package.json, packages/web3/src/connect-modal/style/index.tsx, pnpm-lock.yaml
=> docs: improve try it out style

.changeset/gold-pots-join.md, packages/web3/src/connect-button/style/index.ts
…et to quick
before:
after: 
close: #1035
=> fix(connect-button): width is fit-content when quickConnect

.dumirc.ts
本地有未合并的 packages 且切换分支时，可能会有一些空的包目录，脚本中过滤一下。
=> build: filter out packages that not actually exist

.dumi/theme/common/styles/Icon.tsx
优化一下图标页面样式，方便使用 右键 - 检查元素 的时候直接定位到 svg DOM。现在是定位到了外层元素，不太方便😵‍💫。
=> docs(icons): improve styles by adjust z-index

.changeset/light-adults-relax.md, .fatherrc.base.ts
修改编译目标到 chrome 100，[antd 只支持现代浏览器](https://ant.design/docs/react/introduce-cn#%E5%85%BC%E5%AE%B9%E7%8E%AF%E5%A2%83)，这边支持过低的环境没有意义。
=> build: set targets chrome 100

packages/web3/src/address/index.tsx, packages/web3/src/bitcoin/demos/basic.tsx, packages/web3/src/bitcoin/demos/get-inscriptions.tsx, packages/web3/src/bitcoin/demos/ordinals.tsx, packages/web3/src/bitcoin/demos/send-transfer.tsx, packages/web3/src/bitcoin/demos/sign.tsx, packages/web3/src/browser-link/__tests__/anchor.test.tsx, packages/web3/src/browser-link/index.tsx
Add comments for Props type definitions in various React components.
* **Address Component:**
- Add comments for `AddressProps` type definition in `packages/web3/src/address/index.tsx`.
* **BrowserLink Component:**
- Add comments for `BrowserLinkProps` type definition in `packages/web3/src/browser-link/index.tsx`.
- Add comments for test cases in `packages/web3/src/browser-link/__tests__/anchor.test.tsx`.
* **Bitcoin Demos:**
- Add comments for `ConnectButton` and `Connector` components in `packages/web3/src/bitcoin/demos/basic.tsx`.
- Add comments for `ConnectButton`, `Connector`, and `NFTImage` components in `packages/web3/src/bitcoin/demos/get-inscriptions.tsx`.
- Add comments for `NFTCard` component in `packages/web3/src/bitcoin/demos/ordinals.tsx`.
- Add comments for `ConnectButton` …
=> Add comments for Props type definitions in web3 package

.changeset/moody-elephants-talk.md, packages/wagmi/src/wagmi-provider/index.tsx, packages/web3/src/ethereum/index.md, packages/web3/src/ethereum/index.zh-CN.md
To maintain consistency with the Wagmi, introduces `initialState` and `reconnectOnMount` properties, making component configuration options fully aligned with [WagmiProviderProps](https://github.com/wevm/wagmi/blob/main/packages/react/src/context.ts#L11-L15), facilitating seamless developer migration.
=> feat(web3-wagmi): Add 'initialState' and 'reconnectOnMount' props to WagmiWeb3ConfigProviderProps

.changeset/blue-games-happen.md, packages/wagmi/src/wagmi-provider/__tests__/balance.test.tsx, packages/wagmi/src/wagmi-provider/__tests__/connect-with-universal-wallet.test.tsx, packages/wagmi/src/wagmi-provider/__tests__/connect.test.tsx, packages/wagmi/src/wagmi-provider/__tests__/ens.test.tsx, packages/wagmi/src/wagmi-provider/__tests__/nft.test.tsx, packages/wagmi/src/wagmi-provider/__tests__/switch-chain-unconnected.test.tsx, packages/wagmi/src/wagmi-provider/__tests__/switch-chain.test.tsx, packages/wagmi/src/wagmi-provider/config-provider.tsx, packages/wagmi/src/wagmi-provider/index.tsx
Fixes a spelling error in the `walletFactories` prop name.
The word "Factories" was previously misspelled as "Factorys". This commit corrects the spelling.
=> fix(web3-wagmi): Correct spelling of 'Factories'

.changeset/wise-dodos-juggle.md, docs/guide/ant-design-web3.md, docs/guide/ant-design-web3.zh-CN.md, packages/sui/README.md
=> docs: Update docs for Sui

.changeset/nine-knives-live.md, packages/common/src/types.ts, packages/wagmi/src/wagmi-provider/__tests__/connect.test.tsx, packages/wagmi/src/wagmi-provider/config-provider.tsx, packages/web3/src/types/index.md, packages/web3/src/types/index.zh-CN.md
当多个钱包地址连接之后，onConnected 没有办法判断这种情况，因此需要在 connect 函数中返回全部连接的地址
close #1114
=> feat: add addresses when multi address connected in onConnected

.dumirc.ts, docs/course/contract-compile-deploy.md, docs/course/contract-compile-deploy.zh-CN.md, docs/course/contract-dapp.md
添加水龙头地址 https://zan.top/faucet?chInfo=ch_antdweb3 指引开发者获取测试网 ETH
=> docs: add faucet link

examples/eth-web3js/package.json, examples/ethers-v5/package.json, examples/ethers/package.json, package.json, packages/common/package.json, packages/icons/package.json, packages/web3/package.json, packages/web3/src/address/__tests__/__snapshots__/index.test.tsx.snap, packages/web3/src/connect-button/__tests__/__snapshots__/profile-modal.test.tsx.snap, packages/web3/src/connect-button/__tests__/__snapshots__/tooltip.test.tsx.snap, packages/web3/src/connect-modal/__tests__/__snapshots__/basic.test.tsx.snap, packages/web3/src/connect-modal/__tests__/__snapshots__/simple.test.tsx.snap, packages/web3/src/nft-image/__tests__/__snapshots__/index.test.tsx.snap, packages/web3/src/web3-config-provider/__tests__/__snapshots__/index.test.tsx.snap, pnpm-lock.yaml
经历了很多版本的升级，应该更新一下了。 
1. 期间很多token相关的fix可能有用
2. 以后变更上不会差异太大，好排查升级。
=> chore: bump antd from 5.20.1 to 5.21.5

.dumirc.ts, packages/assets/package.json, packages/bitcoin/package.json, packages/common/package.json, packages/eth-web3js/package.json, packages/ethers-v5/package.json, packages/ethers/package.json, packages/icons/package.json, packages/solana/package.json, packages/sui/package.json, packages/ton/package.json, packages/wagmi/package.json, packages/web3/package.json
=> site: improve seo

docs/course/dev-init.md, docs/course/dev-init.zh-CN.md
由于antd版本升级，rc-input包也需要添加转译配置
✅ Closes: #1241
1.  docs: ✏️ 添加"rc-input"配置，解决antd版本升级问题
由于antd版本升级，rc-input包也需要添加转译配置
2. 根据文档示例启动项目失败，原因是antd升级，transpilePackages 需要额外配置"rc-input"
https://github.com/ant-design/ant-design-web3/issues/1241
=> docs: ✏️ 添加"rc-input"配置，解决antd版本升级问题

packages/web3/src/solana/demos/recommend.tsx, packages/web3/src/solana/index.md, packages/web3/src/solana/index.zh-CN.md
The default RPC was called too many times to be used.
默认的 RPC 调用次数太多而无法使用了。
fix: #1244
=> site(solana): switch the recommend Solana RPC provider

.changeset/shaggy-jokes-fold.md, packages/solana/src/solana-provider/__tests__/balance.test.tsx, packages/solana/src/solana-provider/__tests__/basic.test.tsx, packages/solana/src/solana-provider/__tests__/rpc-provider.test.tsx, packages/solana/src/solana-provider/__tests__/utils.tsx, packages/solana/src/solana-provider/index.tsx
当未提供 `connectionConfig` 属性值时，由于 [ConnectionProvider#config](https://github.com/anza-xyz/wallet-adapter/blob/master/packages/core/react/src/ConnectionProvider.tsx#L14) 属性默认值的缘故，会导致多次渲染。最终导致重复发起获取余额的请求。
这个 PR 优化了相关逻辑，使用 useMemo 缓存了 ConnectionProvider 需要的 props 来减少渲染次数。
---
When the connectionConfig prop value is not provided, the default value of the [ConnectionProvider#config](https://github.com/anza-xyz/wallet-adapter/blob/master/packages/core/react/src/ConnectionProvider.tsx#L14) property causes multiple renders. This eventually leads to duplicate requests for fetching the balance.
This PR optimizes the related logic by using useMemo to cache the props needed by ConnectionProvider, reducing the number of renders.
Before:
=> perf(solana): Optimize rendering times when using default connectionConfig 

.changeset/swift-poets-tell.md, packages/web3/src/hooks/useAccount.ts, packages/web3/src/hooks/useConnection.ts
=> fix: useAccount and useConnection hooks ts type bug

.changeset/hip-vans-laugh.md, packages/solana/src/solana-provider/__tests__/connect-error.test.tsx, packages/solana/src/solana-provider/__tests__/connect.test.tsx, packages/solana/src/solana-provider/config-provider.tsx
修复某些钱包连接过 dapp 后，刷新页面后再次尝试连接，一直处于 pending 状态的问题。
（目前只在 backpack 发现这种现象）
检查发现是由于与底层库的自动重连逻辑有状态冲突导致。
=> fix(solana): Some wallets cannot connect again

.changeset/sour-planets-eat.md, docs/guide/demos/custom-token-web3.tsx, docs/guide/demos/custom-token.tsx, docs/guide/demos/mock.ts, docs/guide/theme.md, docs/guide/theme.zh-CN.md, packages/common/src/web3-config-provider/index.tsx, packages/web3/src/connect-modal/index.md, packages/web3/src/connect-modal/index.zh-CN.md, packages/web3/src/connect-modal/style/index.tsx, packages/web3/src/index.ts, packages/web3/src/theme/useStyle/index.ts, packages/web3/src/web3-config-provider/__tests__/mock/index.ts, packages/web3/src/web3-config-provider/__tests__/theme.test.tsx, packages/web3/src/web3-config-provider/index.tsx
支持更多自定义 DesignToken，通过类似下面这样的方式来自定义更多样式：
```
return (
<Web3ConfigProvider
theme={{
web3Components: {
ConnectModal: {
walletGroupTextColor: 'red',
descriptionColor: 'blue',
},
},
}}
>
<ConnectModal />
</Web3ConfigProvider>
```
=> Support Custome ConnectModal design token

.changeset/spotty-days-end.md, .dumi/components/ShowCase/Connect.tsx, .dumi/components/ShowCase/index.module.less, .dumi/components/Theme/components/Thumbnail.module.less, .dumi/components/Theme/components/Thumbnail.tsx, .dumi/components/Theme/components/tokens.ts, .dumi/components/Theme/index.tsx, docs/guide/demos/custom-token-web3.tsx, docs/guide/demos/tokens.ts, docs/guide/demos/try-it-out/bitcoin.tsx, docs/guide/demos/try-it-out/ethereum.tsx, docs/guide/demos/try-it-out/index.tsx, docs/guide/demos/try-it-out/solana.tsx, docs/guide/demos/try-it-out/sui.tsx, docs/guide/demos/try-it-out/ton.tsx, docs/guide/theme.md, docs/guide/theme.zh-CN.md, packages/web3/src/connect-modal/style/index.tsx, packages/web3/src/index.ts, packages/web3/src/nft-card/style/index.tsx, packages/web3/src/web3-config-provider/index.tsx
添加了一个更复杂的自定义样式，体现出 Ant Design 和 Ant Design Web3 自定义样式的能力：
=> docs: 添加怀旧风格的样式自定义示例

docs/guide/demos/tokens.ts, docs/guide/demos/try-it-out/index.tsx
=> docs: 添加 Material Design 3 风格自定义样式

.github/workflows/preview-deploy.yml
=> fix: deploy yml security issue

packages/web3/src/nft-card/demos/wagmi.tsx
=> docs: NFTCard demo rendering error

packages/web3/src/address/demos/addressPrefix.tsx, packages/web3/src/address/index.md, packages/web3/src/address/index.zh-CN.md
Add addressPrefix demo for Address.
=> docs: Add addressPrefix demo for Address
